/*
 * ESI Meta Spec
 * ESI specs and miscellaneous routes
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.troja.eve.esi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * SSO /verify JSON
 */
@ApiModel(description = "SSO /verify JSON")
public class CharacterInfo implements Serializable {
    private static final long serialVersionUID = 1L;

    @SerializedName("CharacterID")
    private Integer characterID = null;

    @SerializedName("CharacterName")
    private String characterName = null;

    @SerializedName("CharacterOwnerHash")
    private String characterOwnerHash = null;

    @SerializedName("ExpiresOn")
    private String expiresOn = null;

    @SerializedName("IntellectualProperty")
    private String intellectualProperty = null;

    @SerializedName("Scopes")
    private String scopes = null;

    @SerializedName("TokenType")
    private String tokenType = null;

    public CharacterInfo characterID(Integer characterID) {
        this.characterID = characterID;
        return this;
    }

    /**
     * Token owner&#39;s character ID
     * 
     * @return characterID
     **/
    @ApiModelProperty(required = true, value = "Token owner's character ID")
    public Integer getCharacterID() {
        return characterID;
    }

    public void setCharacterID(Integer characterID) {
        this.characterID = characterID;
    }

    public CharacterInfo characterName(String characterName) {
        this.characterName = characterName;
        return this;
    }

    /**
     * Token owner&#39;s character name
     * 
     * @return characterName
     **/
    @ApiModelProperty(value = "Token owner's character name")
    public String getCharacterName() {
        return characterName;
    }

    public void setCharacterName(String characterName) {
        this.characterName = characterName;
    }

    public CharacterInfo characterOwnerHash(String characterOwnerHash) {
        this.characterOwnerHash = characterOwnerHash;
        return this;
    }

    /**
     * Hash of the character&#39;s owner. If the character is sold or otherwise
     * transferred, this will change
     * 
     * @return characterOwnerHash
     **/
    @ApiModelProperty(value = "Hash of the character's owner. If the character is sold or otherwise transferred, this will change")
    public String getCharacterOwnerHash() {
        return characterOwnerHash;
    }

    public void setCharacterOwnerHash(String characterOwnerHash) {
        this.characterOwnerHash = characterOwnerHash;
    }

    public CharacterInfo expiresOn(String expiresOn) {
        this.expiresOn = expiresOn;
        return this;
    }

    /**
     * Expiry time of the token (not RFC3339)
     * 
     * @return expiresOn
     **/
    @ApiModelProperty(value = "Expiry time of the token (not RFC3339)")
    public String getExpiresOn() {
        return expiresOn;
    }

    public void setExpiresOn(String expiresOn) {
        this.expiresOn = expiresOn;
    }

    public CharacterInfo intellectualProperty(String intellectualProperty) {
        this.intellectualProperty = intellectualProperty;
        return this;
    }

    /**
     * The IP which generated the token
     * 
     * @return intellectualProperty
     **/
    @ApiModelProperty(value = "The IP which generated the token")
    public String getIntellectualProperty() {
        return intellectualProperty;
    }

    public void setIntellectualProperty(String intellectualProperty) {
        this.intellectualProperty = intellectualProperty;
    }

    public CharacterInfo scopes(String scopes) {
        this.scopes = scopes;
        return this;
    }

    /**
     * Space separated list of scopes the token is valid for
     * 
     * @return scopes
     **/
    @ApiModelProperty(value = "Space separated list of scopes the token is valid for")
    public String getScopes() {
        return scopes;
    }

    public void setScopes(String scopes) {
        this.scopes = scopes;
    }

    public CharacterInfo tokenType(String tokenType) {
        this.tokenType = tokenType;
        return this;
    }

    /**
     * Type of access token
     * 
     * @return tokenType
     **/
    @ApiModelProperty(value = "Type of access token")
    public String getTokenType() {
        return tokenType;
    }

    public void setTokenType(String tokenType) {
        this.tokenType = tokenType;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CharacterInfo characterInfo = (CharacterInfo) o;
        return Objects.equals(this.characterID, characterInfo.characterID)
                && Objects.equals(this.characterName, characterInfo.characterName)
                && Objects.equals(this.characterOwnerHash, characterInfo.characterOwnerHash)
                && Objects.equals(this.expiresOn, characterInfo.expiresOn)
                && Objects.equals(this.intellectualProperty, characterInfo.intellectualProperty)
                && Objects.equals(this.scopes, characterInfo.scopes)
                && Objects.equals(this.tokenType, characterInfo.tokenType);
    }

    @Override
    public int hashCode() {
        return Objects.hash(characterID, characterName, characterOwnerHash, expiresOn, intellectualProperty, scopes,
                tokenType);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CharacterInfo {\n");

        sb.append("    characterID: ").append(toIndentedString(characterID)).append("\n");
        sb.append("    characterName: ").append(toIndentedString(characterName)).append("\n");
        sb.append("    characterOwnerHash: ").append(toIndentedString(characterOwnerHash)).append("\n");
        sb.append("    expiresOn: ").append(toIndentedString(expiresOn)).append("\n");
        sb.append("    intellectualProperty: ").append(toIndentedString(intellectualProperty)).append("\n");
        sb.append("    scopes: ").append(toIndentedString(scopes)).append("\n");
        sb.append("    tokenType: ").append(toIndentedString(tokenType)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
