/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.33
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.troja.eve.esi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import net.troja.eve.esi.JSON;

/**
 * 200 ok object
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class CharacterFatigueResponse implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String SERIALIZED_NAME_JUMP_FATIGUE_EXPIRE_DATE = "jump_fatigue_expire_date";
    @SerializedName(SERIALIZED_NAME_JUMP_FATIGUE_EXPIRE_DATE)
    private OffsetDateTime jumpFatigueExpireDate;

    public static final String SERIALIZED_NAME_LAST_JUMP_DATE = "last_jump_date";
    @SerializedName(SERIALIZED_NAME_LAST_JUMP_DATE)
    private OffsetDateTime lastJumpDate;

    public static final String SERIALIZED_NAME_LAST_UPDATE_DATE = "last_update_date";
    @SerializedName(SERIALIZED_NAME_LAST_UPDATE_DATE)
    private OffsetDateTime lastUpdateDate;

    public CharacterFatigueResponse() {
    }

    public CharacterFatigueResponse jumpFatigueExpireDate(OffsetDateTime jumpFatigueExpireDate) {

        this.jumpFatigueExpireDate = jumpFatigueExpireDate;
        return this;
    }

    /**
     * Character&#39;s jump fatigue expiry
     * 
     * @return jumpFatigueExpireDate
     **/
    @javax.annotation.Nullable
    public OffsetDateTime getJumpFatigueExpireDate() {
        return jumpFatigueExpireDate;
    }

    public void setJumpFatigueExpireDate(OffsetDateTime jumpFatigueExpireDate) {
        this.jumpFatigueExpireDate = jumpFatigueExpireDate;
    }

    public CharacterFatigueResponse lastJumpDate(OffsetDateTime lastJumpDate) {

        this.lastJumpDate = lastJumpDate;
        return this;
    }

    /**
     * Character&#39;s last jump activation
     * 
     * @return lastJumpDate
     **/
    @javax.annotation.Nullable
    public OffsetDateTime getLastJumpDate() {
        return lastJumpDate;
    }

    public void setLastJumpDate(OffsetDateTime lastJumpDate) {
        this.lastJumpDate = lastJumpDate;
    }

    public CharacterFatigueResponse lastUpdateDate(OffsetDateTime lastUpdateDate) {

        this.lastUpdateDate = lastUpdateDate;
        return this;
    }

    /**
     * Character&#39;s last jump update
     * 
     * @return lastUpdateDate
     **/
    @javax.annotation.Nullable
    public OffsetDateTime getLastUpdateDate() {
        return lastUpdateDate;
    }

    public void setLastUpdateDate(OffsetDateTime lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CharacterFatigueResponse characterFatigueResponse = (CharacterFatigueResponse) o;
        return Objects.equals(this.jumpFatigueExpireDate, characterFatigueResponse.jumpFatigueExpireDate)
                && Objects.equals(this.lastJumpDate, characterFatigueResponse.lastJumpDate)
                && Objects.equals(this.lastUpdateDate, characterFatigueResponse.lastUpdateDate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(jumpFatigueExpireDate, lastJumpDate, lastUpdateDate);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CharacterFatigueResponse {\n");
        sb.append("    jumpFatigueExpireDate: ").append(toIndentedString(jumpFatigueExpireDate)).append("\n");
        sb.append("    lastJumpDate: ").append(toIndentedString(lastJumpDate)).append("\n");
        sb.append("    lastUpdateDate: ").append(toIndentedString(lastUpdateDate)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("jump_fatigue_expire_date");
        openapiFields.add("last_jump_date");
        openapiFields.add("last_update_date");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Object and throws an exception if issues found
     *
     * @param jsonObj
     *            JSON Object
     * @throws IOException
     *             if the JSON Object is invalid with respect to
     *             CharacterFatigueResponse
     */
    public static void validateJsonObject(JsonObject jsonObj) throws IOException {
        if (jsonObj == null) {
            if (!CharacterFatigueResponse.openapiRequiredFields.isEmpty()) { // has
                                                                             // required
                                                                             // fields
                                                                             // but
                                                                             // JSON
                                                                             // object
                                                                             // is
                                                                             // null
                throw new IllegalArgumentException(String.format(
                        "The required field(s) %s in CharacterFatigueResponse is not found in the empty JSON string",
                        CharacterFatigueResponse.openapiRequiredFields.toString()));
            }
        }

        Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
        // check to see if the JSON string contains additional fields
        for (Entry<String, JsonElement> entry : entries) {
            if (!CharacterFatigueResponse.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(
                        String.format(
                                "The field `%s` in the JSON string is not defined in the `CharacterFatigueResponse` properties. JSON: %s",
                                entry.getKey(), jsonObj.toString()));
            }
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!CharacterFatigueResponse.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes
                             // 'CharacterFatigueResponse' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<CharacterFatigueResponse> thisAdapter = gson.getDelegateAdapter(this,
                    TypeToken.get(CharacterFatigueResponse.class));

            return (TypeAdapter<T>) new TypeAdapter<CharacterFatigueResponse>() {
                @Override
                public void write(JsonWriter out, CharacterFatigueResponse value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public CharacterFatigueResponse read(JsonReader in) throws IOException {
                    JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
                    validateJsonObject(jsonObj);
                    return thisAdapter.fromJsonTree(jsonObj);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of CharacterFatigueResponse given an JSON string
     *
     * @param jsonString
     *            JSON string
     * @return An instance of CharacterFatigueResponse
     * @throws IOException
     *             if the JSON string is invalid with respect to
     *             CharacterFatigueResponse
     */
    public static CharacterFatigueResponse fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, CharacterFatigueResponse.class);
    }

    /**
     * Convert an instance of CharacterFatigueResponse to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
