/*
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-26
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.troja.eve.esi.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.troja.eve.esi.JSON;

/**
 * Cursor
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class Cursor implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String SERIALIZED_NAME_AFTER = "after";
    @SerializedName(SERIALIZED_NAME_AFTER)
    @javax.annotation.Nullable
    private String after;

    public static final String SERIALIZED_NAME_BEFORE = "before";
    @SerializedName(SERIALIZED_NAME_BEFORE)
    @javax.annotation.Nullable
    private String before;

    public Cursor() {
    }

    public Cursor after(@javax.annotation.Nullable String after) {
        this.after = after;
        return this;
    }

    /**
     * Cursor to use as &#39;after&#39; in your next request, to continue
     * walking forwards in time.
     * 
     * @return after
     */
    @javax.annotation.Nullable
    public String getAfter() {
        return after;
    }

    public void setAfter(@javax.annotation.Nullable String after) {
        this.after = after;
    }

    public Cursor before(@javax.annotation.Nullable String before) {
        this.before = before;
        return this;
    }

    /**
     * Cursor to use as &#39;before&#39; in your next request, to continue
     * walking backwards in time.
     * 
     * @return before
     */
    @javax.annotation.Nullable
    public String getBefore() {
        return before;
    }

    public void setBefore(@javax.annotation.Nullable String before) {
        this.before = before;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Cursor cursor = (Cursor) o;
        return Objects.equals(this.after, cursor.after) && Objects.equals(this.before, cursor.before);
    }

    @Override
    public int hashCode() {
        return Objects.hash(after, before);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Cursor {\n");
        sb.append("    after: ").append(toIndentedString(after)).append("\n");
        sb.append("    before: ").append(toIndentedString(before)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("after", "before"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(0);
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement
     *            JSON Element
     * @throws IOException
     *             if the JSON Element is invalid with respect to Cursor
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!Cursor.openapiRequiredFields.isEmpty()) { // has required
                                                           // fields but JSON
                                                           // element is null
                throw new IllegalArgumentException(String.format(
                        "The required field(s) %s in Cursor is not found in the empty JSON string",
                        Cursor.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!Cursor.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(
                        "The field `%s` in the JSON string is not defined in the `Cursor` properties. JSON: %s",
                        entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("after") != null && !jsonObj.get("after").isJsonNull())
                && !jsonObj.get("after").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(
                    "Expected the field `after` to be a primitive type in the JSON string but got `%s`",
                    jsonObj.get("after").toString()));
        }
        if ((jsonObj.get("before") != null && !jsonObj.get("before").isJsonNull())
                && !jsonObj.get("before").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(
                    "Expected the field `before` to be a primitive type in the JSON string but got `%s`",
                    jsonObj.get("before").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!Cursor.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'Cursor' and its
                             // subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<Cursor> thisAdapter = gson.getDelegateAdapter(this, TypeToken.get(Cursor.class));

            return (TypeAdapter<T>) new TypeAdapter<Cursor>() {
                @Override
                public void write(JsonWriter out, Cursor value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public Cursor read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of Cursor given an JSON string
     *
     * @param jsonString
     *            JSON string
     * @return An instance of Cursor
     * @throws IOException
     *             if the JSON string is invalid with respect to Cursor
     */
    public static Cursor fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, Cursor.class);
    }

    /**
     * Convert an instance of Cursor to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
