/*
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.troja.eve.esi.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.troja.eve.esi.JSON;

/**
 * GroupResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class GroupResponse implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String SERIALIZED_NAME_CATEGORY_ID = "category_id";
    @SerializedName(SERIALIZED_NAME_CATEGORY_ID)
    @javax.annotation.Nonnull
    private Long categoryId;

    public static final String SERIALIZED_NAME_GROUP_ID = "group_id";
    @SerializedName(SERIALIZED_NAME_GROUP_ID)
    @javax.annotation.Nonnull
    private Long groupId;

    public static final String SERIALIZED_NAME_NAME = "name";
    @SerializedName(SERIALIZED_NAME_NAME)
    @javax.annotation.Nonnull
    private String name;

    public static final String SERIALIZED_NAME_PUBLISHED = "published";
    @SerializedName(SERIALIZED_NAME_PUBLISHED)
    @javax.annotation.Nonnull
    private Boolean published;

    public static final String SERIALIZED_NAME_TYPES = "types";
    @SerializedName(SERIALIZED_NAME_TYPES)
    @javax.annotation.Nonnull
    private List<Long> types;

    public GroupResponse() {
    }

    public GroupResponse categoryId(@javax.annotation.Nonnull Long categoryId) {
        this.categoryId = categoryId;
        return this;
    }

    /**
     * Get categoryId
     * 
     * @return categoryId
     */
    @javax.annotation.Nonnull
    public Long getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(@javax.annotation.Nonnull Long categoryId) {
        this.categoryId = categoryId;
    }

    public GroupResponse groupId(@javax.annotation.Nonnull Long groupId) {
        this.groupId = groupId;
        return this;
    }

    /**
     * Get groupId
     * 
     * @return groupId
     */
    @javax.annotation.Nonnull
    public Long getGroupId() {
        return groupId;
    }

    public void setGroupId(@javax.annotation.Nonnull Long groupId) {
        this.groupId = groupId;
    }

    public GroupResponse name(@javax.annotation.Nonnull String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     * 
     * @return name
     */
    @javax.annotation.Nonnull
    public String getName() {
        return name;
    }

    public void setName(@javax.annotation.Nonnull String name) {
        this.name = name;
    }

    public GroupResponse published(@javax.annotation.Nonnull Boolean published) {
        this.published = published;
        return this;
    }

    /**
     * Get published
     * 
     * @return published
     */
    @javax.annotation.Nonnull
    public Boolean getPublished() {
        return published;
    }

    public void setPublished(@javax.annotation.Nonnull Boolean published) {
        this.published = published;
    }

    public GroupResponse types(@javax.annotation.Nonnull List<Long> types) {
        this.types = types;
        return this;
    }

    public GroupResponse addTypesItem(Long typesItem) {
        if (this.types == null) {
            this.types = new ArrayList<>();
        }

        this.types.add(typesItem);
        return this;
    }

    /**
     * Get types
     * 
     * @return types
     */
    @javax.annotation.Nonnull
    public List<Long> getTypes() {
        return types;
    }

    public void setTypes(@javax.annotation.Nonnull List<Long> types) {
        this.types = types;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GroupResponse groupResponse = (GroupResponse) o;
        return Objects.equals(this.categoryId, groupResponse.categoryId)
                && Objects.equals(this.groupId, groupResponse.groupId) && Objects.equals(this.name, groupResponse.name)
                && Objects.equals(this.published, groupResponse.published)
                && Objects.equals(this.types, groupResponse.types);
    }

    @Override
    public int hashCode() {
        return Objects.hash(categoryId, groupId, name, published, types);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GroupResponse {\n");
        sb.append("    categoryId: ").append(toIndentedString(categoryId)).append("\n");
        sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    published: ").append(toIndentedString(published)).append("\n");
        sb.append("    types: ").append(toIndentedString(types)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("category_id", "group_id", "name", "published", "types"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("category_id", "group_id", "name", "published",
                "types"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement
     *            JSON Element
     * @throws IOException
     *             if the JSON Element is invalid with respect to GroupResponse
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!GroupResponse.openapiRequiredFields.isEmpty()) { // has
                                                                  // required
                                                                  // fields but
                                                                  // JSON
                                                                  // element is
                                                                  // null
                throw new IllegalArgumentException(String.format(
                        "The required field(s) %s in GroupResponse is not found in the empty JSON string",
                        GroupResponse.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!GroupResponse.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(
                        "The field `%s` in the JSON string is not defined in the `GroupResponse` properties. JSON: %s",
                        entry.getKey(), jsonElement.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the
        // JSON string
        for (String requiredField : GroupResponse.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(
                        "The required field `%s` is not found in the JSON string: %s", requiredField,
                        jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("name").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(
                    "Expected the field `name` to be a primitive type in the JSON string but got `%s`",
                    jsonObj.get("name").toString()));
        }
        // ensure the required json array is present
        if (jsonObj.get("types") == null) {
            throw new IllegalArgumentException(
                    "Expected the field `linkedContent` to be an array in the JSON string but got `null`");
        } else if (!jsonObj.get("types").isJsonArray()) {
            throw new IllegalArgumentException(String.format(
                    "Expected the field `types` to be an array in the JSON string but got `%s`", jsonObj.get("types")
                            .toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GroupResponse.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'GroupResponse' and
                             // its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GroupResponse> thisAdapter = gson.getDelegateAdapter(this,
                    TypeToken.get(GroupResponse.class));

            return (TypeAdapter<T>) new TypeAdapter<GroupResponse>() {
                @Override
                public void write(JsonWriter out, GroupResponse value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public GroupResponse read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of GroupResponse given an JSON string
     *
     * @param jsonString
     *            JSON string
     * @return An instance of GroupResponse
     * @throws IOException
     *             if the JSON string is invalid with respect to GroupResponse
     */
    public static GroupResponse fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, GroupResponse.class);
    }

    /**
     * Convert an instance of GroupResponse to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
