/*
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-26
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.troja.eve.esi.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.troja.eve.esi.JSON;

/**
 * item object
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class KillmailByHashResponseVictimItemsItems implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String SERIALIZED_NAME_FLAG = "flag";
    @SerializedName(SERIALIZED_NAME_FLAG)
    @javax.annotation.Nonnull
    private Long flag;

    public static final String SERIALIZED_NAME_ITEM_TYPE_ID = "item_type_id";
    @SerializedName(SERIALIZED_NAME_ITEM_TYPE_ID)
    @javax.annotation.Nonnull
    private Long itemTypeId;

    public static final String SERIALIZED_NAME_QUANTITY_DESTROYED = "quantity_destroyed";
    @SerializedName(SERIALIZED_NAME_QUANTITY_DESTROYED)
    @javax.annotation.Nullable
    private Long quantityDestroyed;

    public static final String SERIALIZED_NAME_QUANTITY_DROPPED = "quantity_dropped";
    @SerializedName(SERIALIZED_NAME_QUANTITY_DROPPED)
    @javax.annotation.Nullable
    private Long quantityDropped;

    public static final String SERIALIZED_NAME_SINGLETON = "singleton";
    @SerializedName(SERIALIZED_NAME_SINGLETON)
    @javax.annotation.Nonnull
    private Long singleton;

    public KillmailByHashResponseVictimItemsItems() {
    }

    public KillmailByHashResponseVictimItemsItems flag(@javax.annotation.Nonnull Long flag) {
        this.flag = flag;
        return this;
    }

    /**
     * Get flag
     * 
     * @return flag
     */
    @javax.annotation.Nonnull
    public Long getFlag() {
        return flag;
    }

    public void setFlag(@javax.annotation.Nonnull Long flag) {
        this.flag = flag;
    }

    public KillmailByHashResponseVictimItemsItems itemTypeId(@javax.annotation.Nonnull Long itemTypeId) {
        this.itemTypeId = itemTypeId;
        return this;
    }

    /**
     * Get itemTypeId
     * 
     * @return itemTypeId
     */
    @javax.annotation.Nonnull
    public Long getItemTypeId() {
        return itemTypeId;
    }

    public void setItemTypeId(@javax.annotation.Nonnull Long itemTypeId) {
        this.itemTypeId = itemTypeId;
    }

    public KillmailByHashResponseVictimItemsItems quantityDestroyed(@javax.annotation.Nullable Long quantityDestroyed) {
        this.quantityDestroyed = quantityDestroyed;
        return this;
    }

    /**
     * Get quantityDestroyed
     * 
     * @return quantityDestroyed
     */
    @javax.annotation.Nullable
    public Long getQuantityDestroyed() {
        return quantityDestroyed;
    }

    public void setQuantityDestroyed(@javax.annotation.Nullable Long quantityDestroyed) {
        this.quantityDestroyed = quantityDestroyed;
    }

    public KillmailByHashResponseVictimItemsItems quantityDropped(@javax.annotation.Nullable Long quantityDropped) {
        this.quantityDropped = quantityDropped;
        return this;
    }

    /**
     * Get quantityDropped
     * 
     * @return quantityDropped
     */
    @javax.annotation.Nullable
    public Long getQuantityDropped() {
        return quantityDropped;
    }

    public void setQuantityDropped(@javax.annotation.Nullable Long quantityDropped) {
        this.quantityDropped = quantityDropped;
    }

    public KillmailByHashResponseVictimItemsItems singleton(@javax.annotation.Nonnull Long singleton) {
        this.singleton = singleton;
        return this;
    }

    /**
     * Get singleton
     * 
     * @return singleton
     */
    @javax.annotation.Nonnull
    public Long getSingleton() {
        return singleton;
    }

    public void setSingleton(@javax.annotation.Nonnull Long singleton) {
        this.singleton = singleton;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        KillmailByHashResponseVictimItemsItems killmailByHashResponseVictimItemsItems = (KillmailByHashResponseVictimItemsItems) o;
        return Objects.equals(this.flag, killmailByHashResponseVictimItemsItems.flag)
                && Objects.equals(this.itemTypeId, killmailByHashResponseVictimItemsItems.itemTypeId)
                && Objects.equals(this.quantityDestroyed, killmailByHashResponseVictimItemsItems.quantityDestroyed)
                && Objects.equals(this.quantityDropped, killmailByHashResponseVictimItemsItems.quantityDropped)
                && Objects.equals(this.singleton, killmailByHashResponseVictimItemsItems.singleton);
    }

    @Override
    public int hashCode() {
        return Objects.hash(flag, itemTypeId, quantityDestroyed, quantityDropped, singleton);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class KillmailByHashResponseVictimItemsItems {\n");
        sb.append("    flag: ").append(toIndentedString(flag)).append("\n");
        sb.append("    itemTypeId: ").append(toIndentedString(itemTypeId)).append("\n");
        sb.append("    quantityDestroyed: ").append(toIndentedString(quantityDestroyed)).append("\n");
        sb.append("    quantityDropped: ").append(toIndentedString(quantityDropped)).append("\n");
        sb.append("    singleton: ").append(toIndentedString(singleton)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("flag", "item_type_id", "quantity_destroyed",
                "quantity_dropped", "singleton"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("flag", "item_type_id", "singleton"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement
     *            JSON Element
     * @throws IOException
     *             if the JSON Element is invalid with respect to
     *             KillmailByHashResponseVictimItemsItems
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!KillmailByHashResponseVictimItemsItems.openapiRequiredFields.isEmpty()) { // has
                                                                                           // required
                                                                                           // fields
                                                                                           // but
                                                                                           // JSON
                                                                                           // element
                                                                                           // is
                                                                                           // null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in KillmailByHashResponseVictimItemsItems is not found in the empty JSON string",
                                KillmailByHashResponseVictimItemsItems.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!KillmailByHashResponseVictimItemsItems.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(
                        String.format(
                                "The field `%s` in the JSON string is not defined in the `KillmailByHashResponseVictimItemsItems` properties. JSON: %s",
                                entry.getKey(), jsonElement.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the
        // JSON string
        for (String requiredField : KillmailByHashResponseVictimItemsItems.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(
                        "The required field `%s` is not found in the JSON string: %s", requiredField,
                        jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!KillmailByHashResponseVictimItemsItems.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes
                             // 'KillmailByHashResponseVictimItemsItems' and its
                             // subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<KillmailByHashResponseVictimItemsItems> thisAdapter = gson.getDelegateAdapter(this,
                    TypeToken.get(KillmailByHashResponseVictimItemsItems.class));

            return (TypeAdapter<T>) new TypeAdapter<KillmailByHashResponseVictimItemsItems>() {
                @Override
                public void write(JsonWriter out, KillmailByHashResponseVictimItemsItems value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public KillmailByHashResponseVictimItemsItems read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of KillmailByHashResponseVictimItemsItems given an
     * JSON string
     *
     * @param jsonString
     *            JSON string
     * @return An instance of KillmailByHashResponseVictimItemsItems
     * @throws IOException
     *             if the JSON string is invalid with respect to
     *             KillmailByHashResponseVictimItemsItems
     */
    public static KillmailByHashResponseVictimItemsItems fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, KillmailByHashResponseVictimItemsItems.class);
    }

    /**
     * Convert an instance of KillmailByHashResponseVictimItemsItems to an JSON
     * string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
