/*
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.troja.eve.esi.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.troja.eve.esi.JSON;

/**
 * MetaChangelogEntry
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class MetaChangelogEntry implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String SERIALIZED_NAME_COMPATIBILITY_DATE = "compatibility_date";
    @SerializedName(SERIALIZED_NAME_COMPATIBILITY_DATE)
    @javax.annotation.Nonnull
    private LocalDate compatibilityDate;

    public static final String SERIALIZED_NAME_DESCRIPTION = "description";
    @SerializedName(SERIALIZED_NAME_DESCRIPTION)
    @javax.annotation.Nonnull
    private String description;

    /**
     * HTTP method of the route
     */
    @JsonAdapter(MethodEnum.Adapter.class)
    public enum MethodEnum {
        /**
     * 
     */
        GET("GET"),

        /**
     * 
     */
        POST("POST"),

        /**
     * 
     */
        PUT("PUT"),

        /**
     * 
     */
        DELETE("DELETE");

        private String value;

        MethodEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static MethodEnum fromValue(String value) {
            for (MethodEnum b : MethodEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            return null;
        }

        public static class Adapter extends TypeAdapter<MethodEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final MethodEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public MethodEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return MethodEnum.fromValue(value);
            }
        }

        public static void validateJsonElement(JsonElement jsonElement) throws IOException {
            String value = jsonElement.getAsString();
            MethodEnum.fromValue(value);
        }
    }

    public static final String SERIALIZED_NAME_METHOD = "method";
    @SerializedName(SERIALIZED_NAME_METHOD)
    @javax.annotation.Nonnull
    private String method;
    private transient MethodEnum methodEnum;

    public static final String SERIALIZED_NAME_PATH = "path";
    @SerializedName(SERIALIZED_NAME_PATH)
    @javax.annotation.Nonnull
    private String path;

    /**
     * Type of the change
     */
    @JsonAdapter(TypeEnum.Adapter.class)
    public enum TypeEnum {
        /**
         * Breaking change
         */
        BREAKING("breaking"),

        /**
         * Non-breaking change
         */
        CHANGED("changed"),

        /**
         * New route
         */
        NEW("new"),

        /**
         * Removed route
         */
        REMOVED("removed");

        private String value;

        TypeEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static TypeEnum fromValue(String value) {
            for (TypeEnum b : TypeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            return null;
        }

        public static class Adapter extends TypeAdapter<TypeEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public TypeEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return TypeEnum.fromValue(value);
            }
        }

        public static void validateJsonElement(JsonElement jsonElement) throws IOException {
            String value = jsonElement.getAsString();
            TypeEnum.fromValue(value);
        }
    }

    public static final String SERIALIZED_NAME_TYPE = "type";
    @SerializedName(SERIALIZED_NAME_TYPE)
    @javax.annotation.Nonnull
    private String type;
    private transient TypeEnum typeEnum;

    public MetaChangelogEntry() {
    }

    public MetaChangelogEntry compatibilityDate(@javax.annotation.Nonnull LocalDate compatibilityDate) {
        this.compatibilityDate = compatibilityDate;
        return this;
    }

    /**
     * Get compatibilityDate
     * 
     * @return compatibilityDate
     */
    @javax.annotation.Nonnull
    public LocalDate getCompatibilityDate() {
        return compatibilityDate;
    }

    public void setCompatibilityDate(@javax.annotation.Nonnull LocalDate compatibilityDate) {
        this.compatibilityDate = compatibilityDate;
    }

    public MetaChangelogEntry description(@javax.annotation.Nonnull String description) {
        this.description = description;
        return this;
    }

    /**
     * Description
     * 
     * @return description
     */
    @javax.annotation.Nonnull
    public String getDescription() {
        return description;
    }

    public void setDescription(@javax.annotation.Nonnull String description) {
        this.description = description;
    }

    public MetaChangelogEntry method(@javax.annotation.Nonnull MethodEnum method) {
        this.methodEnum = method;
        return this;
    }

    public MetaChangelogEntry methodString(@javax.annotation.Nonnull String method) {
        this.method = method;
        return this;
    }

    /**
     * HTTP method of the route
     * 
     * @return method
     */

    public MethodEnum getMethod() {
        if (methodEnum == null) {
            methodEnum = MethodEnum.fromValue(method);
        }
        return methodEnum;
    }

    public String getMethodString() {
        return method;
    }

    public void setMethod(@javax.annotation.Nonnull MethodEnum method) {
        this.methodEnum = method;
    }

    public void setMethodString(@javax.annotation.Nonnull String method) {
        this.method = method;
    }

    public MetaChangelogEntry path(@javax.annotation.Nonnull String path) {
        this.path = path;
        return this;
    }

    /**
     * Path of the route
     * 
     * @return path
     */
    @javax.annotation.Nonnull
    public String getPath() {
        return path;
    }

    public void setPath(@javax.annotation.Nonnull String path) {
        this.path = path;
    }

    public MetaChangelogEntry type(@javax.annotation.Nonnull TypeEnum type) {
        this.typeEnum = type;
        return this;
    }

    public MetaChangelogEntry typeString(@javax.annotation.Nonnull String type) {
        this.type = type;
        return this;
    }

    /**
     * Type of the change
     * 
     * @return type
     */

    public TypeEnum getType() {
        if (typeEnum == null) {
            typeEnum = TypeEnum.fromValue(type);
        }
        return typeEnum;
    }

    public String getTypeString() {
        return type;
    }

    public void setType(@javax.annotation.Nonnull TypeEnum type) {
        this.typeEnum = type;
    }

    public void setTypeString(@javax.annotation.Nonnull String type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MetaChangelogEntry metaChangelogEntry = (MetaChangelogEntry) o;
        return Objects.equals(this.compatibilityDate, metaChangelogEntry.compatibilityDate)
                && Objects.equals(this.description, metaChangelogEntry.description)
                && Objects.equals(this.method, metaChangelogEntry.method)
                && Objects.equals(this.path, metaChangelogEntry.path)
                && Objects.equals(this.type, metaChangelogEntry.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(compatibilityDate, description, method, path, type);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MetaChangelogEntry {\n");
        sb.append("    compatibilityDate: ").append(toIndentedString(compatibilityDate)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    method: ").append(toIndentedString(method)).append("\n");
        sb.append("    path: ").append(toIndentedString(path)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(
                Arrays.asList("compatibility_date", "description", "method", "path", "type"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("compatibility_date", "description", "method",
                "path", "type"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement
     *            JSON Element
     * @throws IOException
     *             if the JSON Element is invalid with respect to
     *             MetaChangelogEntry
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!MetaChangelogEntry.openapiRequiredFields.isEmpty()) { // has
                                                                       // required
                                                                       // fields
                                                                       // but
                                                                       // JSON
                                                                       // element
                                                                       // is
                                                                       // null
                throw new IllegalArgumentException(String.format(
                        "The required field(s) %s in MetaChangelogEntry is not found in the empty JSON string",
                        MetaChangelogEntry.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!MetaChangelogEntry.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(
                        String.format(
                                "The field `%s` in the JSON string is not defined in the `MetaChangelogEntry` properties. JSON: %s",
                                entry.getKey(), jsonElement.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the
        // JSON string
        for (String requiredField : MetaChangelogEntry.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(
                        "The required field `%s` is not found in the JSON string: %s", requiredField,
                        jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("description").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(
                    "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj
                            .get("description").toString()));
        }
        if (!jsonObj.get("method").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(
                    "Expected the field `method` to be a primitive type in the JSON string but got `%s`",
                    jsonObj.get("method").toString()));
        }
        // validate the required field `method`
        MethodEnum.validateJsonElement(jsonObj.get("method"));
        if (!jsonObj.get("path").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(
                    "Expected the field `path` to be a primitive type in the JSON string but got `%s`",
                    jsonObj.get("path").toString()));
        }
        if (!jsonObj.get("type").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(
                    "Expected the field `type` to be a primitive type in the JSON string but got `%s`",
                    jsonObj.get("type").toString()));
        }
        // validate the required field `type`
        TypeEnum.validateJsonElement(jsonObj.get("type"));
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!MetaChangelogEntry.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'MetaChangelogEntry'
                             // and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<MetaChangelogEntry> thisAdapter = gson.getDelegateAdapter(this,
                    TypeToken.get(MetaChangelogEntry.class));

            return (TypeAdapter<T>) new TypeAdapter<MetaChangelogEntry>() {
                @Override
                public void write(JsonWriter out, MetaChangelogEntry value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public MetaChangelogEntry read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of MetaChangelogEntry given an JSON string
     *
     * @param jsonString
     *            JSON string
     * @return An instance of MetaChangelogEntry
     * @throws IOException
     *             if the JSON string is invalid with respect to
     *             MetaChangelogEntry
     */
    public static MetaChangelogEntry fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, MetaChangelogEntry.class);
    }

    /**
     * Convert an instance of MetaChangelogEntry to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
