/*
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2026-08-18
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.troja.eve.esi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import net.troja.eve.esi.model.MilitaryCampaignsObjectivesDetailParticipants;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.troja.eve.esi.JSON;

/**
 * MilitaryCampaignsObjectivesDetailObjective
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class MilitaryCampaignsObjectivesDetailObjective implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String SERIALIZED_NAME_FINISHED = "finished";
    @SerializedName(SERIALIZED_NAME_FINISHED)
    @javax.annotation.Nullable
    private OffsetDateTime finished;

    public static final String SERIALIZED_NAME_ID = "id";
    @SerializedName(SERIALIZED_NAME_ID)
    @javax.annotation.Nonnull
    private UUID id;

    public static final String SERIALIZED_NAME_LAST_MODIFIED = "last_modified";
    @SerializedName(SERIALIZED_NAME_LAST_MODIFIED)
    @javax.annotation.Nonnull
    private OffsetDateTime lastModified;

    public static final String SERIALIZED_NAME_PARTICIPANTS = "participants";
    @SerializedName(SERIALIZED_NAME_PARTICIPANTS)
    @javax.annotation.Nonnull
    private MilitaryCampaignsObjectivesDetailParticipants participants;

    public static final String SERIALIZED_NAME_PROGRESS = "progress";
    @SerializedName(SERIALIZED_NAME_PROGRESS)
    @javax.annotation.Nonnull
    private Long progress;

    public static final String SERIALIZED_NAME_STARTED = "started";
    @SerializedName(SERIALIZED_NAME_STARTED)
    @javax.annotation.Nullable
    private OffsetDateTime started;

    /**
     * Objective&#39;s state
     */
    @JsonAdapter(StateEnum.Adapter.class)
    public enum StateEnum {
        /**
         * An unspecified state
         */
        UNSPECIFIED("Unspecified"),

        /**
         * The campaign is active and accepting contributions
         */
        ACTIVE("Active"),

        /**
         * The campaign met its target before the end date
         */
        COMPLETED("Completed"),

        /**
         * The campaign failed to meet its target before the end date
         */
        EXPIRED("Expired");

        private String value;

        StateEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static StateEnum fromValue(String value) {
            for (StateEnum b : StateEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            return null;
        }

        public static class Adapter extends TypeAdapter<StateEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final StateEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public StateEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return StateEnum.fromValue(value);
            }
        }

        public static void validateJsonElement(JsonElement jsonElement) throws IOException {
            String value = jsonElement.getAsString();
            StateEnum.fromValue(value);
        }
    }

    public static final String SERIALIZED_NAME_STATE = "state";
    @SerializedName(SERIALIZED_NAME_STATE)
    @javax.annotation.Nonnull
    private String state;
    private transient StateEnum stateEnum;

    public MilitaryCampaignsObjectivesDetailObjective() {
    }

    public MilitaryCampaignsObjectivesDetailObjective finished(@javax.annotation.Nullable OffsetDateTime finished) {
        this.finished = finished;
        return this;
    }

    /**
     * Moment the objective transitioned to a non-active state
     * 
     * @return finished
     */
    @javax.annotation.Nullable
    public OffsetDateTime getFinished() {
        return finished;
    }

    public void setFinished(@javax.annotation.Nullable OffsetDateTime finished) {
        this.finished = finished;
    }

    public MilitaryCampaignsObjectivesDetailObjective id(@javax.annotation.Nonnull UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Objective&#39;s ID
     * 
     * @return id
     */
    @javax.annotation.Nonnull
    public UUID getId() {
        return id;
    }

    public void setId(@javax.annotation.Nonnull UUID id) {
        this.id = id;
    }

    public MilitaryCampaignsObjectivesDetailObjective lastModified(@javax.annotation.Nonnull OffsetDateTime lastModified) {
        this.lastModified = lastModified;
        return this;
    }

    /**
     * Objective&#39;s last modified
     * 
     * @return lastModified
     */
    @javax.annotation.Nonnull
    public OffsetDateTime getLastModified() {
        return lastModified;
    }

    public void setLastModified(@javax.annotation.Nonnull OffsetDateTime lastModified) {
        this.lastModified = lastModified;
    }

    public MilitaryCampaignsObjectivesDetailObjective participants(
            @javax.annotation.Nonnull MilitaryCampaignsObjectivesDetailParticipants participants) {
        this.participants = participants;
        return this;
    }

    /**
     * Objective&#39;s participants
     * 
     * @return participants
     */
    @javax.annotation.Nonnull
    public MilitaryCampaignsObjectivesDetailParticipants getParticipants() {
        return participants;
    }

    public void setParticipants(@javax.annotation.Nonnull MilitaryCampaignsObjectivesDetailParticipants participants) {
        this.participants = participants;
    }

    public MilitaryCampaignsObjectivesDetailObjective progress(@javax.annotation.Nonnull Long progress) {
        this.progress = progress;
        return this;
    }

    /**
     * Objective&#39;s progress
     * 
     * @return progress
     */
    @javax.annotation.Nonnull
    public Long getProgress() {
        return progress;
    }

    public void setProgress(@javax.annotation.Nonnull Long progress) {
        this.progress = progress;
    }

    public MilitaryCampaignsObjectivesDetailObjective started(@javax.annotation.Nullable OffsetDateTime started) {
        this.started = started;
        return this;
    }

    /**
     * Moment the objective started
     * 
     * @return started
     */
    @javax.annotation.Nullable
    public OffsetDateTime getStarted() {
        return started;
    }

    public void setStarted(@javax.annotation.Nullable OffsetDateTime started) {
        this.started = started;
    }

    public MilitaryCampaignsObjectivesDetailObjective state(@javax.annotation.Nonnull StateEnum state) {
        this.stateEnum = state;
        return this;
    }

    public MilitaryCampaignsObjectivesDetailObjective stateString(@javax.annotation.Nonnull String state) {
        this.state = state;
        return this;
    }

    /**
     * Objective&#39;s state
     * 
     * @return state
     */

    public StateEnum getState() {
        if (stateEnum == null) {
            stateEnum = StateEnum.fromValue(state);
        }
        return stateEnum;
    }

    public String getStateString() {
        return state;
    }

    public void setState(@javax.annotation.Nonnull StateEnum state) {
        this.stateEnum = state;
    }

    public void setStateString(@javax.annotation.Nonnull String state) {
        this.state = state;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MilitaryCampaignsObjectivesDetailObjective militaryCampaignsObjectivesDetailObjective = (MilitaryCampaignsObjectivesDetailObjective) o;
        return Objects.equals(this.finished, militaryCampaignsObjectivesDetailObjective.finished)
                && Objects.equals(this.id, militaryCampaignsObjectivesDetailObjective.id)
                && Objects.equals(this.lastModified, militaryCampaignsObjectivesDetailObjective.lastModified)
                && Objects.equals(this.participants, militaryCampaignsObjectivesDetailObjective.participants)
                && Objects.equals(this.progress, militaryCampaignsObjectivesDetailObjective.progress)
                && Objects.equals(this.started, militaryCampaignsObjectivesDetailObjective.started)
                && Objects.equals(this.state, militaryCampaignsObjectivesDetailObjective.state);
    }

    @Override
    public int hashCode() {
        return Objects.hash(finished, id, lastModified, participants, progress, started, state);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MilitaryCampaignsObjectivesDetailObjective {\n");
        sb.append("    finished: ").append(toIndentedString(finished)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
        sb.append("    participants: ").append(toIndentedString(participants)).append("\n");
        sb.append("    progress: ").append(toIndentedString(progress)).append("\n");
        sb.append("    started: ").append(toIndentedString(started)).append("\n");
        sb.append("    state: ").append(toIndentedString(state)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("finished", "id", "last_modified", "participants",
                "progress", "started", "state"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "last_modified", "participants", "progress",
                "state"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement
     *            JSON Element
     * @throws IOException
     *             if the JSON Element is invalid with respect to
     *             MilitaryCampaignsObjectivesDetailObjective
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!MilitaryCampaignsObjectivesDetailObjective.openapiRequiredFields.isEmpty()) { // has
                                                                                               // required
                                                                                               // fields
                                                                                               // but
                                                                                               // JSON
                                                                                               // element
                                                                                               // is
                                                                                               // null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in MilitaryCampaignsObjectivesDetailObjective is not found in the empty JSON string",
                                MilitaryCampaignsObjectivesDetailObjective.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!MilitaryCampaignsObjectivesDetailObjective.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(
                        String.format(
                                "The field `%s` in the JSON string is not defined in the `MilitaryCampaignsObjectivesDetailObjective` properties. JSON: %s",
                                entry.getKey(), jsonElement.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the
        // JSON string
        for (String requiredField : MilitaryCampaignsObjectivesDetailObjective.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(
                        "The required field `%s` is not found in the JSON string: %s", requiredField,
                        jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("id").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(
                    "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id")
                            .toString()));
        }
        // validate the required field `participants`
        MilitaryCampaignsObjectivesDetailParticipants.validateJsonElement(jsonObj.get("participants"));
        if (!jsonObj.get("state").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(
                    "Expected the field `state` to be a primitive type in the JSON string but got `%s`",
                    jsonObj.get("state").toString()));
        }
        // validate the required field `state`
        StateEnum.validateJsonElement(jsonObj.get("state"));
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!MilitaryCampaignsObjectivesDetailObjective.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes
                             // 'MilitaryCampaignsObjectivesDetailObjective' and
                             // its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<MilitaryCampaignsObjectivesDetailObjective> thisAdapter = gson.getDelegateAdapter(this,
                    TypeToken.get(MilitaryCampaignsObjectivesDetailObjective.class));

            return (TypeAdapter<T>) new TypeAdapter<MilitaryCampaignsObjectivesDetailObjective>() {
                @Override
                public void write(JsonWriter out, MilitaryCampaignsObjectivesDetailObjective value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public MilitaryCampaignsObjectivesDetailObjective read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of MilitaryCampaignsObjectivesDetailObjective given an
     * JSON string
     *
     * @param jsonString
     *            JSON string
     * @return An instance of MilitaryCampaignsObjectivesDetailObjective
     * @throws IOException
     *             if the JSON string is invalid with respect to
     *             MilitaryCampaignsObjectivesDetailObjective
     */
    public static MilitaryCampaignsObjectivesDetailObjective fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, MilitaryCampaignsObjectivesDetailObjective.class);
    }

    /**
     * Convert an instance of MilitaryCampaignsObjectivesDetailObjective to an
     * JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
