/*
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2026-08-18
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.troja.eve.esi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.troja.eve.esi.JSON;

/**
 * MilitaryCampaignsDetailCampaign
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class MilitaryCampaignsDetailCampaign implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String SERIALIZED_NAME_FINISHED = "finished";
    @SerializedName(SERIALIZED_NAME_FINISHED)
    @javax.annotation.Nullable
    private OffsetDateTime finished;

    public static final String SERIALIZED_NAME_ID = "id";
    @SerializedName(SERIALIZED_NAME_ID)
    @javax.annotation.Nonnull
    private UUID id;

    public static final String SERIALIZED_NAME_PROGRESS = "progress";
    @SerializedName(SERIALIZED_NAME_PROGRESS)
    @javax.annotation.Nonnull
    private Long progress;

    public static final String SERIALIZED_NAME_STARTED = "started";
    @SerializedName(SERIALIZED_NAME_STARTED)
    @javax.annotation.Nullable
    private OffsetDateTime started;

    /**
     * Campaign&#39;s state
     */
    @JsonAdapter(StateEnum.Adapter.class)
    public enum StateEnum {
        /**
         * An unspecified state
         */
        UNSPECIFIED("Unspecified"),

        /**
         * The campaign is active and accepting contributions
         */
        ACTIVE("Active"),

        /**
         * The campaign met its target before the end date
         */
        COMPLETED("Completed"),

        /**
         * The campaign failed to meet its target before the end date
         */
        EXPIRED("Expired");

        private String value;

        StateEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static StateEnum fromValue(String value) {
            for (StateEnum b : StateEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            return null;
        }

        public static class Adapter extends TypeAdapter<StateEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final StateEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public StateEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return StateEnum.fromValue(value);
            }
        }

        public static void validateJsonElement(JsonElement jsonElement) throws IOException {
            String value = jsonElement.getAsString();
            StateEnum.fromValue(value);
        }
    }

    public static final String SERIALIZED_NAME_STATE = "state";
    @SerializedName(SERIALIZED_NAME_STATE)
    @javax.annotation.Nonnull
    private String state;
    private transient StateEnum stateEnum;

    public MilitaryCampaignsDetailCampaign() {
    }

    public MilitaryCampaignsDetailCampaign finished(@javax.annotation.Nullable OffsetDateTime finished) {
        this.finished = finished;
        return this;
    }

    /**
     * Moment the campaign transitioned to a non-active state
     * 
     * @return finished
     */
    @javax.annotation.Nullable
    public OffsetDateTime getFinished() {
        return finished;
    }

    public void setFinished(@javax.annotation.Nullable OffsetDateTime finished) {
        this.finished = finished;
    }

    public MilitaryCampaignsDetailCampaign id(@javax.annotation.Nonnull UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Campaign&#39;s ID
     * 
     * @return id
     */
    @javax.annotation.Nonnull
    public UUID getId() {
        return id;
    }

    public void setId(@javax.annotation.Nonnull UUID id) {
        this.id = id;
    }

    public MilitaryCampaignsDetailCampaign progress(@javax.annotation.Nonnull Long progress) {
        this.progress = progress;
        return this;
    }

    /**
     * Campaign&#39;s progress
     * 
     * @return progress
     */
    @javax.annotation.Nonnull
    public Long getProgress() {
        return progress;
    }

    public void setProgress(@javax.annotation.Nonnull Long progress) {
        this.progress = progress;
    }

    public MilitaryCampaignsDetailCampaign started(@javax.annotation.Nullable OffsetDateTime started) {
        this.started = started;
        return this;
    }

    /**
     * Moment the campaign started
     * 
     * @return started
     */
    @javax.annotation.Nullable
    public OffsetDateTime getStarted() {
        return started;
    }

    public void setStarted(@javax.annotation.Nullable OffsetDateTime started) {
        this.started = started;
    }

    public MilitaryCampaignsDetailCampaign state(@javax.annotation.Nonnull StateEnum state) {
        this.stateEnum = state;
        return this;
    }

    public MilitaryCampaignsDetailCampaign stateString(@javax.annotation.Nonnull String state) {
        this.state = state;
        return this;
    }

    /**
     * Campaign&#39;s state
     * 
     * @return state
     */

    public StateEnum getState() {
        if (stateEnum == null) {
            stateEnum = StateEnum.fromValue(state);
        }
        return stateEnum;
    }

    public String getStateString() {
        return state;
    }

    public void setState(@javax.annotation.Nonnull StateEnum state) {
        this.stateEnum = state;
    }

    public void setStateString(@javax.annotation.Nonnull String state) {
        this.state = state;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MilitaryCampaignsDetailCampaign militaryCampaignsDetailCampaign = (MilitaryCampaignsDetailCampaign) o;
        return Objects.equals(this.finished, militaryCampaignsDetailCampaign.finished)
                && Objects.equals(this.id, militaryCampaignsDetailCampaign.id)
                && Objects.equals(this.progress, militaryCampaignsDetailCampaign.progress)
                && Objects.equals(this.started, militaryCampaignsDetailCampaign.started)
                && Objects.equals(this.state, militaryCampaignsDetailCampaign.state);
    }

    @Override
    public int hashCode() {
        return Objects.hash(finished, id, progress, started, state);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MilitaryCampaignsDetailCampaign {\n");
        sb.append("    finished: ").append(toIndentedString(finished)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    progress: ").append(toIndentedString(progress)).append("\n");
        sb.append("    started: ").append(toIndentedString(started)).append("\n");
        sb.append("    state: ").append(toIndentedString(state)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("finished", "id", "progress", "started", "state"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "progress", "state"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement
     *            JSON Element
     * @throws IOException
     *             if the JSON Element is invalid with respect to
     *             MilitaryCampaignsDetailCampaign
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!MilitaryCampaignsDetailCampaign.openapiRequiredFields.isEmpty()) { // has
                                                                                    // required
                                                                                    // fields
                                                                                    // but
                                                                                    // JSON
                                                                                    // element
                                                                                    // is
                                                                                    // null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in MilitaryCampaignsDetailCampaign is not found in the empty JSON string",
                                MilitaryCampaignsDetailCampaign.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!MilitaryCampaignsDetailCampaign.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(
                        String.format(
                                "The field `%s` in the JSON string is not defined in the `MilitaryCampaignsDetailCampaign` properties. JSON: %s",
                                entry.getKey(), jsonElement.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the
        // JSON string
        for (String requiredField : MilitaryCampaignsDetailCampaign.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(
                        "The required field `%s` is not found in the JSON string: %s", requiredField,
                        jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("id").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(
                    "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id")
                            .toString()));
        }
        if (!jsonObj.get("state").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(
                    "Expected the field `state` to be a primitive type in the JSON string but got `%s`",
                    jsonObj.get("state").toString()));
        }
        // validate the required field `state`
        StateEnum.validateJsonElement(jsonObj.get("state"));
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!MilitaryCampaignsDetailCampaign.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes
                             // 'MilitaryCampaignsDetailCampaign' and its
                             // subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<MilitaryCampaignsDetailCampaign> thisAdapter = gson.getDelegateAdapter(this,
                    TypeToken.get(MilitaryCampaignsDetailCampaign.class));

            return (TypeAdapter<T>) new TypeAdapter<MilitaryCampaignsDetailCampaign>() {
                @Override
                public void write(JsonWriter out, MilitaryCampaignsDetailCampaign value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public MilitaryCampaignsDetailCampaign read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of MilitaryCampaignsDetailCampaign given an JSON
     * string
     *
     * @param jsonString
     *            JSON string
     * @return An instance of MilitaryCampaignsDetailCampaign
     * @throws IOException
     *             if the JSON string is invalid with respect to
     *             MilitaryCampaignsDetailCampaign
     */
    public static MilitaryCampaignsDetailCampaign fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, MilitaryCampaignsDetailCampaign.class);
    }

    /**
     * Convert an instance of MilitaryCampaignsDetailCampaign to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
