/*
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.troja.eve.esi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.troja.eve.esi.JSON;

/**
 * PublicContractsItemsResponseInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class PublicContractsItemsResponseInner implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String SERIALIZED_NAME_IS_BLUEPRINT_COPY = "is_blueprint_copy";
    @SerializedName(SERIALIZED_NAME_IS_BLUEPRINT_COPY)
    @javax.annotation.Nullable
    private Boolean isBlueprintCopy;

    public static final String SERIALIZED_NAME_IS_INCLUDED = "is_included";
    @SerializedName(SERIALIZED_NAME_IS_INCLUDED)
    @javax.annotation.Nonnull
    private Boolean isIncluded;

    public static final String SERIALIZED_NAME_ITEM_ID = "item_id";
    @SerializedName(SERIALIZED_NAME_ITEM_ID)
    @javax.annotation.Nullable
    private Long itemId;

    public static final String SERIALIZED_NAME_MATERIAL_EFFICIENCY = "material_efficiency";
    @SerializedName(SERIALIZED_NAME_MATERIAL_EFFICIENCY)
    @javax.annotation.Nullable
    private Long materialEfficiency;

    public static final String SERIALIZED_NAME_QUANTITY = "quantity";
    @SerializedName(SERIALIZED_NAME_QUANTITY)
    @javax.annotation.Nonnull
    private Long quantity;

    public static final String SERIALIZED_NAME_RECORD_ID = "record_id";
    @SerializedName(SERIALIZED_NAME_RECORD_ID)
    @javax.annotation.Nonnull
    private Long recordId;

    public static final String SERIALIZED_NAME_RUNS = "runs";
    @SerializedName(SERIALIZED_NAME_RUNS)
    @javax.annotation.Nullable
    private Long runs;

    public static final String SERIALIZED_NAME_TIME_EFFICIENCY = "time_efficiency";
    @SerializedName(SERIALIZED_NAME_TIME_EFFICIENCY)
    @javax.annotation.Nullable
    private Long timeEfficiency;

    public static final String SERIALIZED_NAME_TYPE_ID = "type_id";
    @SerializedName(SERIALIZED_NAME_TYPE_ID)
    @javax.annotation.Nonnull
    private Long typeId;

    public PublicContractsItemsResponseInner() {
    }

    public PublicContractsItemsResponseInner isBlueprintCopy(@javax.annotation.Nullable Boolean isBlueprintCopy) {
        this.isBlueprintCopy = isBlueprintCopy;
        return this;
    }

    /**
     * Get isBlueprintCopy
     * 
     * @return isBlueprintCopy
     */
    @javax.annotation.Nullable
    public Boolean getIsBlueprintCopy() {
        return isBlueprintCopy;
    }

    public void setIsBlueprintCopy(@javax.annotation.Nullable Boolean isBlueprintCopy) {
        this.isBlueprintCopy = isBlueprintCopy;
    }

    public PublicContractsItemsResponseInner isIncluded(@javax.annotation.Nonnull Boolean isIncluded) {
        this.isIncluded = isIncluded;
        return this;
    }

    /**
     * true if the contract issuer has submitted this item with the contract,
     * false if the isser is asking for this item in the contract
     * 
     * @return isIncluded
     */
    @javax.annotation.Nonnull
    public Boolean getIsIncluded() {
        return isIncluded;
    }

    public void setIsIncluded(@javax.annotation.Nonnull Boolean isIncluded) {
        this.isIncluded = isIncluded;
    }

    public PublicContractsItemsResponseInner itemId(@javax.annotation.Nullable Long itemId) {
        this.itemId = itemId;
        return this;
    }

    /**
     * Unique ID for the item being sold. Not present if item is being requested
     * by contract rather than sold with contract
     * 
     * @return itemId
     */
    @javax.annotation.Nullable
    public Long getItemId() {
        return itemId;
    }

    public void setItemId(@javax.annotation.Nullable Long itemId) {
        this.itemId = itemId;
    }

    public PublicContractsItemsResponseInner materialEfficiency(@javax.annotation.Nullable Long materialEfficiency) {
        this.materialEfficiency = materialEfficiency;
        return this;
    }

    /**
     * Material Efficiency Level of the blueprint
     * 
     * @return materialEfficiency
     */
    @javax.annotation.Nullable
    public Long getMaterialEfficiency() {
        return materialEfficiency;
    }

    public void setMaterialEfficiency(@javax.annotation.Nullable Long materialEfficiency) {
        this.materialEfficiency = materialEfficiency;
    }

    public PublicContractsItemsResponseInner quantity(@javax.annotation.Nonnull Long quantity) {
        this.quantity = quantity;
        return this;
    }

    /**
     * Number of items in the stack
     * 
     * @return quantity
     */
    @javax.annotation.Nonnull
    public Long getQuantity() {
        return quantity;
    }

    public void setQuantity(@javax.annotation.Nonnull Long quantity) {
        this.quantity = quantity;
    }

    public PublicContractsItemsResponseInner recordId(@javax.annotation.Nonnull Long recordId) {
        this.recordId = recordId;
        return this;
    }

    /**
     * Unique ID for the item, used by the contract system
     * 
     * @return recordId
     */
    @javax.annotation.Nonnull
    public Long getRecordId() {
        return recordId;
    }

    public void setRecordId(@javax.annotation.Nonnull Long recordId) {
        this.recordId = recordId;
    }

    public PublicContractsItemsResponseInner runs(@javax.annotation.Nullable Long runs) {
        this.runs = runs;
        return this;
    }

    /**
     * Number of runs remaining if the blueprint is a copy, -1 if it is an
     * original
     * 
     * @return runs
     */
    @javax.annotation.Nullable
    public Long getRuns() {
        return runs;
    }

    public void setRuns(@javax.annotation.Nullable Long runs) {
        this.runs = runs;
    }

    public PublicContractsItemsResponseInner timeEfficiency(@javax.annotation.Nullable Long timeEfficiency) {
        this.timeEfficiency = timeEfficiency;
        return this;
    }

    /**
     * Time Efficiency Level of the blueprint
     * 
     * @return timeEfficiency
     */
    @javax.annotation.Nullable
    public Long getTimeEfficiency() {
        return timeEfficiency;
    }

    public void setTimeEfficiency(@javax.annotation.Nullable Long timeEfficiency) {
        this.timeEfficiency = timeEfficiency;
    }

    public PublicContractsItemsResponseInner typeId(@javax.annotation.Nonnull Long typeId) {
        this.typeId = typeId;
        return this;
    }

    /**
     * Type ID for item
     * 
     * @return typeId
     */
    @javax.annotation.Nonnull
    public Long getTypeId() {
        return typeId;
    }

    public void setTypeId(@javax.annotation.Nonnull Long typeId) {
        this.typeId = typeId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PublicContractsItemsResponseInner publicContractsItemsResponseInner = (PublicContractsItemsResponseInner) o;
        return Objects.equals(this.isBlueprintCopy, publicContractsItemsResponseInner.isBlueprintCopy)
                && Objects.equals(this.isIncluded, publicContractsItemsResponseInner.isIncluded)
                && Objects.equals(this.itemId, publicContractsItemsResponseInner.itemId)
                && Objects.equals(this.materialEfficiency, publicContractsItemsResponseInner.materialEfficiency)
                && Objects.equals(this.quantity, publicContractsItemsResponseInner.quantity)
                && Objects.equals(this.recordId, publicContractsItemsResponseInner.recordId)
                && Objects.equals(this.runs, publicContractsItemsResponseInner.runs)
                && Objects.equals(this.timeEfficiency, publicContractsItemsResponseInner.timeEfficiency)
                && Objects.equals(this.typeId, publicContractsItemsResponseInner.typeId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(isBlueprintCopy, isIncluded, itemId, materialEfficiency, quantity, recordId, runs,
                timeEfficiency, typeId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PublicContractsItemsResponseInner {\n");
        sb.append("    isBlueprintCopy: ").append(toIndentedString(isBlueprintCopy)).append("\n");
        sb.append("    isIncluded: ").append(toIndentedString(isIncluded)).append("\n");
        sb.append("    itemId: ").append(toIndentedString(itemId)).append("\n");
        sb.append("    materialEfficiency: ").append(toIndentedString(materialEfficiency)).append("\n");
        sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
        sb.append("    recordId: ").append(toIndentedString(recordId)).append("\n");
        sb.append("    runs: ").append(toIndentedString(runs)).append("\n");
        sb.append("    timeEfficiency: ").append(toIndentedString(timeEfficiency)).append("\n");
        sb.append("    typeId: ").append(toIndentedString(typeId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("is_blueprint_copy", "is_included", "item_id",
                "material_efficiency", "quantity", "record_id", "runs", "time_efficiency", "type_id"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("is_included", "quantity", "record_id", "type_id"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement
     *            JSON Element
     * @throws IOException
     *             if the JSON Element is invalid with respect to
     *             PublicContractsItemsResponseInner
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!PublicContractsItemsResponseInner.openapiRequiredFields.isEmpty()) { // has
                                                                                      // required
                                                                                      // fields
                                                                                      // but
                                                                                      // JSON
                                                                                      // element
                                                                                      // is
                                                                                      // null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in PublicContractsItemsResponseInner is not found in the empty JSON string",
                                PublicContractsItemsResponseInner.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!PublicContractsItemsResponseInner.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(
                        String.format(
                                "The field `%s` in the JSON string is not defined in the `PublicContractsItemsResponseInner` properties. JSON: %s",
                                entry.getKey(), jsonElement.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the
        // JSON string
        for (String requiredField : PublicContractsItemsResponseInner.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(
                        "The required field `%s` is not found in the JSON string: %s", requiredField,
                        jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!PublicContractsItemsResponseInner.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes
                             // 'PublicContractsItemsResponseInner' and its
                             // subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<PublicContractsItemsResponseInner> thisAdapter = gson.getDelegateAdapter(this,
                    TypeToken.get(PublicContractsItemsResponseInner.class));

            return (TypeAdapter<T>) new TypeAdapter<PublicContractsItemsResponseInner>() {
                @Override
                public void write(JsonWriter out, PublicContractsItemsResponseInner value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public PublicContractsItemsResponseInner read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of PublicContractsItemsResponseInner given an JSON
     * string
     *
     * @param jsonString
     *            JSON string
     * @return An instance of PublicContractsItemsResponseInner
     * @throws IOException
     *             if the JSON string is invalid with respect to
     *             PublicContractsItemsResponseInner
     */
    public static PublicContractsItemsResponseInner fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, PublicContractsItemsResponseInner.class);
    }

    /**
     * Convert an instance of PublicContractsItemsResponseInner to an JSON
     * string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
