/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.33
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.troja.eve.esi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.troja.eve.esi.JSON;

/**
 * 200 ok object
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class PublicContractsItemsResponse implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String SERIALIZED_NAME_IS_BLUEPRINT_COPY = "is_blueprint_copy";
    @SerializedName(SERIALIZED_NAME_IS_BLUEPRINT_COPY)
    @javax.annotation.Nullable
    private Boolean isBlueprintCopy;

    public static final String SERIALIZED_NAME_IS_INCLUDED = "is_included";
    @SerializedName(SERIALIZED_NAME_IS_INCLUDED)
    @javax.annotation.Nonnull
    private Boolean isIncluded;

    public static final String SERIALIZED_NAME_ITEM_ID = "item_id";
    @SerializedName(SERIALIZED_NAME_ITEM_ID)
    @javax.annotation.Nullable
    private Long itemId;

    public static final String SERIALIZED_NAME_MATERIAL_EFFICIENCY = "material_efficiency";
    @SerializedName(SERIALIZED_NAME_MATERIAL_EFFICIENCY)
    @javax.annotation.Nullable
    private Integer materialEfficiency;

    public static final String SERIALIZED_NAME_QUANTITY = "quantity";
    @SerializedName(SERIALIZED_NAME_QUANTITY)
    @javax.annotation.Nonnull
    private Integer quantity;

    public static final String SERIALIZED_NAME_RECORD_ID = "record_id";
    @SerializedName(SERIALIZED_NAME_RECORD_ID)
    @javax.annotation.Nonnull
    private Long recordId;

    public static final String SERIALIZED_NAME_RUNS = "runs";
    @SerializedName(SERIALIZED_NAME_RUNS)
    @javax.annotation.Nullable
    private Integer runs;

    public static final String SERIALIZED_NAME_TIME_EFFICIENCY = "time_efficiency";
    @SerializedName(SERIALIZED_NAME_TIME_EFFICIENCY)
    @javax.annotation.Nullable
    private Integer timeEfficiency;

    public static final String SERIALIZED_NAME_TYPE_ID = "type_id";
    @SerializedName(SERIALIZED_NAME_TYPE_ID)
    @javax.annotation.Nonnull
    private Integer typeId;

    public PublicContractsItemsResponse() {
    }

    public PublicContractsItemsResponse isBlueprintCopy(@javax.annotation.Nullable Boolean isBlueprintCopy) {
        this.isBlueprintCopy = isBlueprintCopy;
        return this;
    }

    /**
     * is_blueprint_copy boolean
     * 
     * @return isBlueprintCopy
     */
    @javax.annotation.Nullable
    public Boolean getIsBlueprintCopy() {
        return isBlueprintCopy;
    }

    public void setIsBlueprintCopy(@javax.annotation.Nullable Boolean isBlueprintCopy) {
        this.isBlueprintCopy = isBlueprintCopy;
    }

    public PublicContractsItemsResponse isIncluded(@javax.annotation.Nonnull Boolean isIncluded) {
        this.isIncluded = isIncluded;
        return this;
    }

    /**
     * true if the contract issuer has submitted this item with the contract,
     * false if the isser is asking for this item in the contract
     * 
     * @return isIncluded
     */
    @javax.annotation.Nonnull
    public Boolean getIsIncluded() {
        return isIncluded;
    }

    public void setIsIncluded(@javax.annotation.Nonnull Boolean isIncluded) {
        this.isIncluded = isIncluded;
    }

    public PublicContractsItemsResponse itemId(@javax.annotation.Nullable Long itemId) {
        this.itemId = itemId;
        return this;
    }

    /**
     * Unique ID for the item being sold. Not present if item is being requested
     * by contract rather than sold with contract
     * 
     * @return itemId
     */
    @javax.annotation.Nullable
    public Long getItemId() {
        return itemId;
    }

    public void setItemId(@javax.annotation.Nullable Long itemId) {
        this.itemId = itemId;
    }

    public PublicContractsItemsResponse materialEfficiency(@javax.annotation.Nullable Integer materialEfficiency) {
        this.materialEfficiency = materialEfficiency;
        return this;
    }

    /**
     * Material Efficiency Level of the blueprint minimum: 0 maximum: 25
     * 
     * @return materialEfficiency
     */
    @javax.annotation.Nullable
    public Integer getMaterialEfficiency() {
        return materialEfficiency;
    }

    public void setMaterialEfficiency(@javax.annotation.Nullable Integer materialEfficiency) {
        this.materialEfficiency = materialEfficiency;
    }

    public PublicContractsItemsResponse quantity(@javax.annotation.Nonnull Integer quantity) {
        this.quantity = quantity;
        return this;
    }

    /**
     * Number of items in the stack
     * 
     * @return quantity
     */
    @javax.annotation.Nonnull
    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(@javax.annotation.Nonnull Integer quantity) {
        this.quantity = quantity;
    }

    public PublicContractsItemsResponse recordId(@javax.annotation.Nonnull Long recordId) {
        this.recordId = recordId;
        return this;
    }

    /**
     * Unique ID for the item, used by the contract system
     * 
     * @return recordId
     */
    @javax.annotation.Nonnull
    public Long getRecordId() {
        return recordId;
    }

    public void setRecordId(@javax.annotation.Nonnull Long recordId) {
        this.recordId = recordId;
    }

    public PublicContractsItemsResponse runs(@javax.annotation.Nullable Integer runs) {
        this.runs = runs;
        return this;
    }

    /**
     * Number of runs remaining if the blueprint is a copy, -1 if it is an
     * original minimum: -1
     * 
     * @return runs
     */
    @javax.annotation.Nullable
    public Integer getRuns() {
        return runs;
    }

    public void setRuns(@javax.annotation.Nullable Integer runs) {
        this.runs = runs;
    }

    public PublicContractsItemsResponse timeEfficiency(@javax.annotation.Nullable Integer timeEfficiency) {
        this.timeEfficiency = timeEfficiency;
        return this;
    }

    /**
     * Time Efficiency Level of the blueprint minimum: 0 maximum: 20
     * 
     * @return timeEfficiency
     */
    @javax.annotation.Nullable
    public Integer getTimeEfficiency() {
        return timeEfficiency;
    }

    public void setTimeEfficiency(@javax.annotation.Nullable Integer timeEfficiency) {
        this.timeEfficiency = timeEfficiency;
    }

    public PublicContractsItemsResponse typeId(@javax.annotation.Nonnull Integer typeId) {
        this.typeId = typeId;
        return this;
    }

    /**
     * Type ID for item
     * 
     * @return typeId
     */
    @javax.annotation.Nonnull
    public Integer getTypeId() {
        return typeId;
    }

    public void setTypeId(@javax.annotation.Nonnull Integer typeId) {
        this.typeId = typeId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PublicContractsItemsResponse publicContractsItemsResponse = (PublicContractsItemsResponse) o;
        return Objects.equals(this.isBlueprintCopy, publicContractsItemsResponse.isBlueprintCopy)
                && Objects.equals(this.isIncluded, publicContractsItemsResponse.isIncluded)
                && Objects.equals(this.itemId, publicContractsItemsResponse.itemId)
                && Objects.equals(this.materialEfficiency, publicContractsItemsResponse.materialEfficiency)
                && Objects.equals(this.quantity, publicContractsItemsResponse.quantity)
                && Objects.equals(this.recordId, publicContractsItemsResponse.recordId)
                && Objects.equals(this.runs, publicContractsItemsResponse.runs)
                && Objects.equals(this.timeEfficiency, publicContractsItemsResponse.timeEfficiency)
                && Objects.equals(this.typeId, publicContractsItemsResponse.typeId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(isBlueprintCopy, isIncluded, itemId, materialEfficiency, quantity, recordId, runs,
                timeEfficiency, typeId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PublicContractsItemsResponse {\n");
        sb.append("    isBlueprintCopy: ").append(toIndentedString(isBlueprintCopy)).append("\n");
        sb.append("    isIncluded: ").append(toIndentedString(isIncluded)).append("\n");
        sb.append("    itemId: ").append(toIndentedString(itemId)).append("\n");
        sb.append("    materialEfficiency: ").append(toIndentedString(materialEfficiency)).append("\n");
        sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
        sb.append("    recordId: ").append(toIndentedString(recordId)).append("\n");
        sb.append("    runs: ").append(toIndentedString(runs)).append("\n");
        sb.append("    timeEfficiency: ").append(toIndentedString(timeEfficiency)).append("\n");
        sb.append("    typeId: ").append(toIndentedString(typeId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("is_blueprint_copy");
        openapiFields.add("is_included");
        openapiFields.add("item_id");
        openapiFields.add("material_efficiency");
        openapiFields.add("quantity");
        openapiFields.add("record_id");
        openapiFields.add("runs");
        openapiFields.add("time_efficiency");
        openapiFields.add("type_id");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
        openapiRequiredFields.add("is_included");
        openapiRequiredFields.add("quantity");
        openapiRequiredFields.add("record_id");
        openapiRequiredFields.add("type_id");
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement
     *            JSON Element
     * @throws IOException
     *             if the JSON Element is invalid with respect to
     *             PublicContractsItemsResponse
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!PublicContractsItemsResponse.openapiRequiredFields.isEmpty()) { // has
                                                                                 // required
                                                                                 // fields
                                                                                 // but
                                                                                 // JSON
                                                                                 // element
                                                                                 // is
                                                                                 // null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in PublicContractsItemsResponse is not found in the empty JSON string",
                                PublicContractsItemsResponse.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!PublicContractsItemsResponse.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(
                        String.format(
                                "The field `%s` in the JSON string is not defined in the `PublicContractsItemsResponse` properties. JSON: %s",
                                entry.getKey(), jsonElement.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the
        // JSON string
        for (String requiredField : PublicContractsItemsResponse.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(
                        "The required field `%s` is not found in the JSON string: %s", requiredField,
                        jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!PublicContractsItemsResponse.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes
                             // 'PublicContractsItemsResponse' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<PublicContractsItemsResponse> thisAdapter = gson.getDelegateAdapter(this,
                    TypeToken.get(PublicContractsItemsResponse.class));

            return (TypeAdapter<T>) new TypeAdapter<PublicContractsItemsResponse>() {
                @Override
                public void write(JsonWriter out, PublicContractsItemsResponse value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public PublicContractsItemsResponse read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of PublicContractsItemsResponse given an JSON string
     *
     * @param jsonString
     *            JSON string
     * @return An instance of PublicContractsItemsResponse
     * @throws IOException
     *             if the JSON string is invalid with respect to
     *             PublicContractsItemsResponse
     */
    public static PublicContractsItemsResponse fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, PublicContractsItemsResponse.class);
    }

    /**
     * Convert an instance of PublicContractsItemsResponse to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
