/*
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package net.troja.eve.esi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.troja.eve.esi.JSON;

/**
 * SchematicResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class SchematicResponse implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String SERIALIZED_NAME_CYCLE_TIME = "cycle_time";
    @SerializedName(SERIALIZED_NAME_CYCLE_TIME)
    @javax.annotation.Nonnull
    private Long cycleTime;

    public static final String SERIALIZED_NAME_SCHEMATIC_NAME = "schematic_name";
    @SerializedName(SERIALIZED_NAME_SCHEMATIC_NAME)
    @javax.annotation.Nonnull
    private String schematicName;

    public SchematicResponse() {
    }

    public SchematicResponse cycleTime(@javax.annotation.Nonnull Long cycleTime) {
        this.cycleTime = cycleTime;
        return this;
    }

    /**
     * Time in seconds to process a run
     * 
     * @return cycleTime
     */
    @javax.annotation.Nonnull
    public Long getCycleTime() {
        return cycleTime;
    }

    public void setCycleTime(@javax.annotation.Nonnull Long cycleTime) {
        this.cycleTime = cycleTime;
    }

    public SchematicResponse schematicName(@javax.annotation.Nonnull String schematicName) {
        this.schematicName = schematicName;
        return this;
    }

    /**
     * Get schematicName
     * 
     * @return schematicName
     */
    @javax.annotation.Nonnull
    public String getSchematicName() {
        return schematicName;
    }

    public void setSchematicName(@javax.annotation.Nonnull String schematicName) {
        this.schematicName = schematicName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SchematicResponse schematicResponse = (SchematicResponse) o;
        return Objects.equals(this.cycleTime, schematicResponse.cycleTime)
                && Objects.equals(this.schematicName, schematicResponse.schematicName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(cycleTime, schematicName);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SchematicResponse {\n");
        sb.append("    cycleTime: ").append(toIndentedString(cycleTime)).append("\n");
        sb.append("    schematicName: ").append(toIndentedString(schematicName)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("cycle_time", "schematic_name"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("cycle_time", "schematic_name"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement
     *            JSON Element
     * @throws IOException
     *             if the JSON Element is invalid with respect to
     *             SchematicResponse
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!SchematicResponse.openapiRequiredFields.isEmpty()) { // has
                                                                      // required
                                                                      // fields
                                                                      // but
                                                                      // JSON
                                                                      // element
                                                                      // is null
                throw new IllegalArgumentException(String.format(
                        "The required field(s) %s in SchematicResponse is not found in the empty JSON string",
                        SchematicResponse.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!SchematicResponse.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(
                        String.format(
                                "The field `%s` in the JSON string is not defined in the `SchematicResponse` properties. JSON: %s",
                                entry.getKey(), jsonElement.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the
        // JSON string
        for (String requiredField : SchematicResponse.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(
                        "The required field `%s` is not found in the JSON string: %s", requiredField,
                        jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("schematic_name").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(
                    "Expected the field `schematic_name` to be a primitive type in the JSON string but got `%s`",
                    jsonObj.get("schematic_name").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!SchematicResponse.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'SchematicResponse'
                             // and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<SchematicResponse> thisAdapter = gson.getDelegateAdapter(this,
                    TypeToken.get(SchematicResponse.class));

            return (TypeAdapter<T>) new TypeAdapter<SchematicResponse>() {
                @Override
                public void write(JsonWriter out, SchematicResponse value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public SchematicResponse read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of SchematicResponse given an JSON string
     *
     * @param jsonString
     *            JSON string
     * @return An instance of SchematicResponse
     * @throws IOException
     *             if the JSON string is invalid with respect to
     *             SchematicResponse
     */
    public static SchematicResponse fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, SchematicResponse.class);
    }

    /**
     * Convert an instance of SchematicResponse to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
