/*
 * EVE Stable Infrastructure (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.troja.eve.esi.api;

import net.troja.eve.esi.ApiException;
import net.troja.eve.esi.model.CharacterLoyaltyPointsResponseInner;
import net.troja.eve.esi.model.LoyaltyStoreOffersResponseInner;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * API tests for LoyaltyApi
 */
public class LoyaltyApiTest extends GeneralApiTest {

    private final LoyaltyApi api = new LoyaltyApi();

    @BeforeEach
    public void setUp() {
        api.setApiClient(apiClient);
    }
    
    /**
     * Get loyalty points
     *
     * Return a list of loyalty points for all corporations the character has worked for
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCharacterLoyaltyPointsTest() throws ApiException {
        String acceptLanguage = null;
        String ifNoneMatch = null;
        String xTenant = null;
        List<CharacterLoyaltyPointsResponseInner> response = api.getCharacterLoyaltyPoints(characterId, CorporationApi.COMPATIBILITY_DATE, acceptLanguage, ifNoneMatch, xTenant);
        assertThat(response).isNotEmpty();
        assertThat(response.get(0).getLoyaltyPoints()).isGreaterThan(0);
    }

    /**
     * List loyalty store offers
     *
     * Return a list of offers from a specific corporation&#39;s loyalty store  This route expires daily at 11:05
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLoyaltyStoresCorporationIdOffersTest() throws ApiException {
        Long corporationId = 1000035L;
        String acceptLanguage = null;
        String ifNoneMatch = null;
        String xTenant = null;
        List<LoyaltyStoreOffersResponseInner> response = api.getLoyaltyStoresCorporationIdOffers(corporationId, CorporationApi.COMPATIBILITY_DATE, acceptLanguage, ifNoneMatch, xTenant);
        assertThat(response).isNotEmpty();
        assertThat(response.get(0).getLpCost()).isGreaterThan(0);
    }

}
