/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.troja.eve.esi.api;

import net.troja.eve.esi.ApiException;
import net.troja.eve.esi.model.CharacterSearchResponse;
import net.troja.eve.esi.model.SearchResponse;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SearchApi
 */
public class SearchApiTest {

    private final SearchApi api = new SearchApi();

    
    /**
     * Search on a string
     *
     * Search for entities that match a given sub-string.  ---  Alternate route: &#x60;/v2/characters/{character_id}/search/&#x60;   ---  This route is cached for up to 3600 seconds  SSO Scope: esi-search.search_structures.v1
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdSearchTest() throws ApiException {
        Integer characterId = null;
        String search = null;
        List<String> categories = null;
        String language = null;
        Boolean strict = null;
        String datasource = null;
        // CharacterSearchResponse response = api.getCharactersCharacterIdSearch(characterId, search, categories, language, strict, datasource);

        // TODO: test validations
    }
    
    /**
     * Search on a string
     *
     * Search for entities that match a given sub-string.  ---  Alternate route: &#x60;/v1/search/&#x60;  Alternate route: &#x60;/legacy/search/&#x60;   ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSearchTest() throws ApiException {
        String search = null;
        List<String> categories = null;
        String language = null;
        Boolean strict = null;
        String datasource = null;
        // SearchResponse response = api.getSearch(search, categories, language, strict, datasource);

        // TODO: test validations
    }
    
}
