/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.2.7.dev1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package net.troja.eve.esi.api;

import static org.hamcrest.CoreMatchers.notNullValue;
import static org.hamcrest.Matchers.greaterThan;
import static org.junit.Assert.assertThat;

import java.util.List;

import org.junit.Test;

import net.troja.eve.esi.ApiException;
import net.troja.eve.esi.model.SovereigntyCampaignsResponse;
import net.troja.eve.esi.model.SovereigntyStructuresResponse;

/**
 * API tests for SovereigntyApi
 */
public class SovereigntyApiTest extends GeneralApiTest {

    private final SovereigntyApi api = new SovereigntyApi();

    /**
     * List sovereignty campaigns
     *
     * Shows sovereignty data for campaigns. --- Alternate route:
     * &#x60;/v1/sovereignty/campaigns/&#x60; Alternate route:
     * &#x60;/legacy/sovereignty/campaigns/&#x60; Alternate route:
     * &#x60;/dev/sovereignty/campaigns/&#x60; --- This route is cached for up
     * to 5 seconds
     *
     * @throws ApiException
     *             if the Api call fails
     */
    @Test
    public void getSovereigntyCampaignsTest() throws ApiException {
        final List<SovereigntyCampaignsResponse> response = api.getSovereigntyCampaigns(DATASOURCE);

        assertThat(response, notNullValue());
        assertThat(response.size(), greaterThan(0));
        final SovereigntyCampaignsResponse sovereigntyResponse = response.get(0);
        assertThat(sovereigntyResponse.getSolarSystemId(), greaterThan(0));
    }

    /**
     * List sovereignty structures
     *
     * Shows sovereignty data for structures. --- Alternate route:
     * &#x60;/v1/sovereignty/structures/&#x60; Alternate route:
     * &#x60;/legacy/sovereignty/structures/&#x60; Alternate route:
     * &#x60;/dev/sovereignty/structures/&#x60; --- This route is cached for up
     * to 120 seconds
     *
     * @throws ApiException
     *             if the Api call fails
     */
    @Test
    public void getSovereigntyStructuresTest() throws ApiException {
        final List<SovereigntyStructuresResponse> response = api.getSovereigntyStructures(DATASOURCE);

        assertThat(response, notNullValue());
        assertThat(response.size(), greaterThan(0));
        final SovereigntyStructuresResponse structuresResponse = response.get(0);
        assertThat(structuresResponse.getSolarSystemId(), greaterThan(0));
    }
}
