s/Get"/Response"/g

# Schemas
# jq . esi.json | sed -n -e 's#.*/schemas/\([^"]*\)"#\1#p' | grep -v Error | sort -u
s/CharactersCharacterIdMailMailId/Mail/g
s/CharactersCharacterIdMailLabels/MailLabels/g
s/LabelsLabelId/Label/g
s/CharactersCharacterIdMailLists/MailLists/g
s/CharactersCharacterIdMail/Mails/g
s/AlliancesAllianceId/Alliance/g
s/CharactersAffiliationPost/CharacterAffiliationResponse/g
s/CharactersCharacterIdAgentsResearch/CharacterResearchAgents/g
s/CharactersCharacterId/Character/g
s/CalendarEventId/CalendarEvent/g
s/CharacterContacts/Contacts/g
s/ContractsContractId/Contract/g
s/CharacterCorporationhistory/CharacterCorporationHistory/g
s/KillmailsRecent/Killmails/g
s/CharacterPlanetsPlanetId/CharacterPlanet/g
s/ContractsPublic/PublicContracts/g
s/ContractIdResponse/Response/g
s/ContractsRegionId/Contracts/g
s/CorporationCorporationId/Corporation/g
s/ObserversObserverId/Observer/g
s/CorporationsCorporationId/Corporation/g
s/CorporationAlliancehistory/CorporationAllianceshistory/g
s/CorporationAssetsLocationsPost/CorporationAssetsLocationsResponse/g
s/CorporationAssetsNamesPost/CorporationAssetsNamesReponse/g
s/CorporationMembertracking/CorporationMemberTracking/g
s/CorporationStarbasesStarbaseId/CorporationStarbase/g
s/WalletsDivision/Wallet/g
s/DogmaAttributesAttributeId/DogmaAttribute/g
s/DogmaDynamicItemsTypeIdItemId/DogmaDynamicItems/g
s/DogmaEffectsEffectId/DogmaEffect/g
s/FleetsFleetId/Fleet/g
s/MembersMemberId/Member/g
s/SquadsSquadId/Squad/g
s/WingsWingId/Wing/g
s/Fw/FactionWarfare/g
s/ObserversObserverId/Observer/g
s/KillmailsKillmailIdKillmailHash/KillmailByHash/g
s/LoyaltyStoresCorporationIdOffers/LoyaltyStoreOffers/g
s/MarketsRegionId/MarketRegion/g
s/Markets/Market/g
s/MarketGroupsMarketGroupId/MarketGroup/g
s/StructuresStructureId/Structure/g
s/AsteroidBeltsAsteroidBeltId/AsteroidBelts/g
s/UniverseAncestries/Ancestries/g
s/UniverseAsteroidBelts/AsteroidBelts/g
s/UniverseBloodlines/Bloodlines/g
s/UniverseCategoriesCategoryId/Category/g
s/UniverseCategories/Categories/g
s/UniverseConstellationsConstellationId/Constellation/g
s/UniverseConstellations/Constellations/g
s/ConstellationsConstellationId/Constellation/g
s/UniverseFactions/Factions/g
s/UniverseGraphicsGraphicId/Graphic/g
s/GraphicsGraphicId/Graphic/g
s/UniverseGraphics/Graphics/g
s/UniverseGroupsGroupId/Group/g
s/UniverseGroups/Groups/g
s/UniverseMoonsMoonId/Moon/g
s/UniversePlanetsPlanetId/Planet/g
s/UniverseRaces/Races/g
s/UniverseRegionsRegionId/Region/g
s/UniverseRegions/Regions/g
s/UniverseSchematicsSchematicId/Schematic/g
s/UniverseStargatesStargateId/Stargate/g
s/UniverseStarsStarId/Star/g
s/UniverseStationsStationId/Station/g
s/UniverseStructures/Structures/g
s/UniverseStructuresStructureId/Structure/g
s/UniverseSystemJumps/SystemJumps/g
s/UniverseSystemKills/SystemKills/g
s/UniverseSystemsSystemId/System/g
s/UniverseSystems/Systems/g
s/UniverseTypesTypeId/Type/g
s/UniverseTypes/Types/g
s/UniverseNamesPost/NamesResponse/g
s/UniverseNames/Names/g
s/WarsWarIdKillmails/WarKillmails/g
s/WarsWarId/War/g
