/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.17
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.troja.eve.esi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CorporationMiningObserversResponse
 */
public class CorporationMiningObserversResponseTest {
    private final CorporationMiningObserversResponse model = new CorporationMiningObserversResponse();

    /**
     * Model tests for CorporationMiningObserversResponse
     */
    @Test
    public void testCorporationMiningObserversResponse() {
        // TODO: test CorporationMiningObserversResponse
    }

    /**
     * Test the property 'lastUpdated'
     */
    @Test
    public void lastUpdatedTest() {
        // TODO: test lastUpdated
    }

    /**
     * Test the property 'observerId'
     */
    @Test
    public void observerIdTest() {
        // TODO: test observerId
    }

    /**
     * Test the property 'observerType'
     */
    @Test
    public void observerTypeTest() {
        // TODO: test observerType
    }

}
