/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.17
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.troja.eve.esi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CorporationMemberTrackingResponse
 */
public class CorporationMemberTrackingResponseTest {
    private final CorporationMemberTrackingResponse model = new CorporationMemberTrackingResponse();

    /**
     * Model tests for CorporationMemberTrackingResponse
     */
    @Test
    public void testCorporationMemberTrackingResponse() {
        // TODO: test CorporationMemberTrackingResponse
    }

    /**
     * Test the property 'baseId'
     */
    @Test
    public void baseIdTest() {
        // TODO: test baseId
    }

    /**
     * Test the property 'characterId'
     */
    @Test
    public void characterIdTest() {
        // TODO: test characterId
    }

    /**
     * Test the property 'locationId'
     */
    @Test
    public void locationIdTest() {
        // TODO: test locationId
    }

    /**
     * Test the property 'logoffDate'
     */
    @Test
    public void logoffDateTest() {
        // TODO: test logoffDate
    }

    /**
     * Test the property 'logonDate'
     */
    @Test
    public void logonDateTest() {
        // TODO: test logonDate
    }

    /**
     * Test the property 'shipTypeId'
     */
    @Test
    public void shipTypeIdTest() {
        // TODO: test shipTypeId
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

}
