/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.troja.eve.esi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DogmaDynamicAttribute
 */
public class DogmaDynamicAttributeTest {
    private final DogmaDynamicAttribute model = new DogmaDynamicAttribute();

    /**
     * Model tests for DogmaDynamicAttribute
     */
    @Test
    public void testDogmaDynamicAttribute() {
        // TODO: test DogmaDynamicAttribute
    }

    /**
     * Test the property 'attributeId'
     */
    @Test
    public void attributeIdTest() {
        // TODO: test attributeId
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
