/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.17
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.troja.eve.esi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import net.troja.eve.esi.model.FactionWarfareLeaderboardCorporationsKills;
import net.troja.eve.esi.model.FactionWarfareLeaderboardCorporationsVictoryPoints;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FactionWarfareLeaderboardCorporationsResponse
 */
public class FactionWarfareLeaderboardCorporationsResponseTest {
    private final FactionWarfareLeaderboardCorporationsResponse model = new FactionWarfareLeaderboardCorporationsResponse();

    /**
     * Model tests for FactionWarfareLeaderboardCorporationsResponse
     */
    @Test
    public void testFactionWarfareLeaderboardCorporationsResponse() {
        // TODO: test FactionWarfareLeaderboardCorporationsResponse
    }

    /**
     * Test the property 'kills'
     */
    @Test
    public void killsTest() {
        // TODO: test kills
    }

    /**
     * Test the property 'victoryPoints'
     */
    @Test
    public void victoryPointsTest() {
        // TODO: test victoryPoints
    }

}
