/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.17
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.troja.eve.esi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FactionWarfareLeaderboardCorporationActiveTotalKills
 */
public class FactionWarfareLeaderboardCorporationActiveTotalKillsTest {
    private final FactionWarfareLeaderboardCorporationActiveTotalKills model = new FactionWarfareLeaderboardCorporationActiveTotalKills();

    /**
     * Model tests for FactionWarfareLeaderboardCorporationActiveTotalKills
     */
    @Test
    public void testFactionWarfareLeaderboardCorporationActiveTotalKills() {
        // TODO: test FactionWarfareLeaderboardCorporationActiveTotalKills
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'corporationId'
     */
    @Test
    public void corporationIdTest() {
        // TODO: test corporationId
    }

}
