/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.17
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.troja.eve.esi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FleetMembersResponse
 */
public class FleetMembersResponseTest {
    private final FleetMembersResponse model = new FleetMembersResponse();

    /**
     * Model tests for FleetMembersResponse
     */
    @Test
    public void testFleetMembersResponse() {
        // TODO: test FleetMembersResponse
    }

    /**
     * Test the property 'characterId'
     */
    @Test
    public void characterIdTest() {
        // TODO: test characterId
    }

    /**
     * Test the property 'joinTime'
     */
    @Test
    public void joinTimeTest() {
        // TODO: test joinTime
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

    /**
     * Test the property 'roleName'
     */
    @Test
    public void roleNameTest() {
        // TODO: test roleName
    }

    /**
     * Test the property 'shipTypeId'
     */
    @Test
    public void shipTypeIdTest() {
        // TODO: test shipTypeId
    }

    /**
     * Test the property 'solarSystemId'
     */
    @Test
    public void solarSystemIdTest() {
        // TODO: test solarSystemId
    }

    /**
     * Test the property 'squadId'
     */
    @Test
    public void squadIdTest() {
        // TODO: test squadId
    }

    /**
     * Test the property 'stationId'
     */
    @Test
    public void stationIdTest() {
        // TODO: test stationId
    }

    /**
     * Test the property 'takesFleetWarp'
     */
    @Test
    public void takesFleetWarpTest() {
        // TODO: test takesFleetWarp
    }

    /**
     * Test the property 'wingId'
     */
    @Test
    public void wingIdTest() {
        // TODO: test wingId
    }

}
