/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.troja.eve.esi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import net.troja.eve.esi.model.RequiredItem;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for LoyaltyStoreOffersResponse
 */
public class LoyaltyStoreOffersResponseTest {
    private final LoyaltyStoreOffersResponse model = new LoyaltyStoreOffersResponse();

    /**
     * Model tests for LoyaltyStoreOffersResponse
     */
    @Test
    public void testLoyaltyStoreOffersResponse() {
        // TODO: test LoyaltyStoreOffersResponse
    }

    /**
     * Test the property 'lpCost'
     */
    @Test
    public void lpCostTest() {
        // TODO: test lpCost
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'typeId'
     */
    @Test
    public void typeIdTest() {
        // TODO: test typeId
    }

    /**
     * Test the property 'iskCost'
     */
    @Test
    public void iskCostTest() {
        // TODO: test iskCost
    }

    /**
     * Test the property 'akCost'
     */
    @Test
    public void akCostTest() {
        // TODO: test akCost
    }

    /**
     * Test the property 'offerId'
     */
    @Test
    public void offerIdTest() {
        // TODO: test offerId
    }

    /**
     * Test the property 'requiredItems'
     */
    @Test
    public void requiredItemsTest() {
        // TODO: test requiredItems
    }

}
