/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.troja.eve.esi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import net.troja.eve.esi.model.PlanetContent;
import net.troja.eve.esi.model.PlanetExtractorDetails;
import net.troja.eve.esi.model.PlanetFactoryDetails;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PlanetPin
 */
public class PlanetPinTest {
    private final PlanetPin model = new PlanetPin();

    /**
     * Model tests for PlanetPin
     */
    @Test
    public void testPlanetPin() {
        // TODO: test PlanetPin
    }

    /**
     * Test the property 'installTime'
     */
    @Test
    public void installTimeTest() {
        // TODO: test installTime
    }

    /**
     * Test the property 'factoryDetails'
     */
    @Test
    public void factoryDetailsTest() {
        // TODO: test factoryDetails
    }

    /**
     * Test the property 'lastCycleStart'
     */
    @Test
    public void lastCycleStartTest() {
        // TODO: test lastCycleStart
    }

    /**
     * Test the property 'contents'
     */
    @Test
    public void contentsTest() {
        // TODO: test contents
    }

    /**
     * Test the property 'schematicId'
     */
    @Test
    public void schematicIdTest() {
        // TODO: test schematicId
    }

    /**
     * Test the property 'typeId'
     */
    @Test
    public void typeIdTest() {
        // TODO: test typeId
    }

    /**
     * Test the property 'latitude'
     */
    @Test
    public void latitudeTest() {
        // TODO: test latitude
    }

    /**
     * Test the property 'expiryTime'
     */
    @Test
    public void expiryTimeTest() {
        // TODO: test expiryTime
    }

    /**
     * Test the property 'pinId'
     */
    @Test
    public void pinIdTest() {
        // TODO: test pinId
    }

    /**
     * Test the property 'extractorDetails'
     */
    @Test
    public void extractorDetailsTest() {
        // TODO: test extractorDetails
    }

    /**
     * Test the property 'longitude'
     */
    @Test
    public void longitudeTest() {
        // TODO: test longitude
    }

}
