openapi: 3.0.1
info:
  description: An OpenAPI for EVE Online
  title: EVE Swagger Interface
  version: "1.33"
servers:
- url: https://esi.evetech.net/
paths:
  /v1/alliances/:
    get:
      description: |-
        List all active player alliances

        ---

        This route is cached for up to 3600 seconds
      operationId: get_alliances
      summary: List all alliances
      tags:
      - Alliance
      x-alternate-versions:
      - dev
      - legacy
      - v1
      - v2
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v1/alliances/{alliance_id}/contacts/labels/:
    get:
      description: |-
        Return custom labels for an alliance's contacts

        ---

        This route is cached for up to 300 seconds

        SSO Scope: esi-alliances.read_contacts.v1
      operationId: get_alliances_alliance_id_contacts_labels
      security:
      - evesso:
        - esi-alliances.read_contacts.v1
      summary: Get alliance contact labels
      tags:
      - Contacts
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 300
      x-accepts:
      - application/json
  /v1/alliances/{alliance_id}/corporations/:
    get:
      description: |-
        List all current member corporations of an alliance

        ---

        This route is cached for up to 3600 seconds
      operationId: get_alliances_alliance_id_corporations
      summary: List alliance's corporations
      tags:
      - Alliance
      x-alternate-versions:
      - dev
      - legacy
      - v1
      - v2
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v1/alliances/{alliance_id}/icons/:
    get:
      description: |-
        Get the icon urls for a alliance

        ---

        This route expires daily at 11:05
      operationId: get_alliances_alliance_id_icons
      summary: Get alliance icon
      tags:
      - Alliance
      x-alternate-versions:
      - dev
      - legacy
      - v1
      - v2
      x-accepts:
      - application/json
  /v1/characters/affiliation/:
    post:
      description: |-
        Bulk lookup of character IDs to corporation, alliance and faction

        ---

        This route is cached for up to 3600 seconds
      operationId: post_characters_affiliation
      summary: Character affiliation
      tags:
      - Character
      x-alternate-versions:
      - dev
      - legacy
      - v1
      - v2
      x-cached-seconds: 3600
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/characters/{character_id}/assets/names/:
    post:
      description: |-
        Return names for a set of item ids, which you can get from character assets endpoint. Typically used for items that can customize names, like containers or ships.

        ---


        SSO Scope: esi-assets.read_assets.v1
      operationId: post_characters_character_id_assets_names
      security:
      - evesso:
        - esi-assets.read_assets.v1
      summary: Get character asset names
      tags:
      - Assets
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/characters/{character_id}/attributes/:
    get:
      description: |-
        Return attributes of a character

        ---

        This route is cached for up to 120 seconds

        SSO Scope: esi-skills.read_skills.v1
      operationId: get_characters_character_id_attributes
      security:
      - evesso:
        - esi-skills.read_skills.v1
      summary: Get character attributes
      tags:
      - Skills
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 120
      x-accepts:
      - application/json
  /v1/characters/{character_id}/calendar/:
    get:
      description: |-
        Get 50 event summaries from the calendar. If no from_event ID is given, the resource will return the next 50 chronological event summaries from now. If a from_event ID is specified, it will return the next 50 chronological event summaries from after that event

        ---

        This route is cached for up to 5 seconds

        SSO Scope: esi-calendar.read_calendar_events.v1
      operationId: get_characters_character_id_calendar
      security:
      - evesso:
        - esi-calendar.read_calendar_events.v1
      summary: List calendar event summaries
      tags:
      - Calendar
      x-alternate-versions:
      - dev
      - legacy
      - v1
      - v2
      x-cached-seconds: 5
      x-accepts:
      - application/json
  /v1/characters/{character_id}/calendar/{event_id}/attendees/:
    get:
      description: |-
        Get all invited attendees for a given event

        ---

        This route is cached for up to 600 seconds

        SSO Scope: esi-calendar.read_calendar_events.v1
      operationId: get_characters_character_id_calendar_event_id_attendees
      security:
      - evesso:
        - esi-calendar.read_calendar_events.v1
      summary: Get attendees
      tags:
      - Calendar
      x-alternate-versions:
      - dev
      - legacy
      - v1
      - v2
      x-cached-seconds: 600
      x-accepts:
      - application/json
  /v1/characters/{character_id}/contacts/:
    delete:
      description: |-
        Bulk delete contacts

        ---


        SSO Scope: esi-characters.write_contacts.v1
      operationId: delete_characters_character_id_contacts
      security:
      - evesso:
        - esi-characters.write_contacts.v1
      summary: Delete contacts
      tags:
      - Contacts
      x-alternate-versions:
      - dev
      - legacy
      - v1
      - v2
      x-accepts:
      - application/json
  /v1/characters/{character_id}/contacts/labels/:
    get:
      description: |-
        Return custom labels for a character's contacts

        ---

        This route is cached for up to 300 seconds

        SSO Scope: esi-characters.read_contacts.v1
      operationId: get_characters_character_id_contacts_labels
      security:
      - evesso:
        - esi-characters.read_contacts.v1
      summary: Get contact labels
      tags:
      - Contacts
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 300
      x-accepts:
      - application/json
  /v1/characters/{character_id}/contracts/:
    get:
      description: |-
        Returns contracts available to a character, only if the character is issuer, acceptor or assignee. Only returns contracts no older than 30 days, or if the status is "in_progress".

        ---

        This route is cached for up to 300 seconds
      operationId: get_characters_character_id_contracts
      security:
      - evesso:
        - esi-contracts.read_character_contracts.v1
      summary: Get contracts
      tags:
      - Contracts
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 300
      x-accepts:
      - application/json
  /v1/characters/{character_id}/contracts/{contract_id}/bids/:
    get:
      description: |-
        Lists bids on a particular auction contract

        ---

        This route is cached for up to 300 seconds

        SSO Scope: esi-contracts.read_character_contracts.v1
      operationId: get_characters_character_id_contracts_contract_id_bids
      security:
      - evesso:
        - esi-contracts.read_character_contracts.v1
      summary: Get contract bids
      tags:
      - Contracts
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 300
      x-accepts:
      - application/json
  /v1/characters/{character_id}/contracts/{contract_id}/items/:
    get:
      description: |-
        Lists items of a particular contract

        ---

        This route is cached for up to 3600 seconds

        SSO Scope: esi-contracts.read_corporation_contracts.v1

        SSO Scope: esi-contracts.read_character_contracts.v1
      operationId: get_characters_character_id_contracts_contract_id_items
      security:
      - evesso:
        - esi-contracts.read_character_contracts.v1
      summary: Get contract items
      tags:
      - Contracts
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v1/characters/{character_id}/fittings/:
    post:
      description: |-
        Save a new fitting for a character

        ---


        SSO Scope: esi-fittings.write_fittings.v1
      operationId: post_characters_character_id_fittings
      security:
      - evesso:
        - esi-fittings.write_fittings.v1
      summary: Create fitting
      tags:
      - Fittings
      x-alternate-versions:
      - dev
      - legacy
      - v1
      - v2
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/characters/{character_id}/fittings/{fitting_id}/:
    delete:
      description: |-
        Delete a fitting from a character

        ---


        SSO Scope: esi-fittings.write_fittings.v1
      operationId: delete_characters_character_id_fittings_fitting_id
      security:
      - evesso:
        - esi-fittings.write_fittings.v1
      summary: Delete fitting
      tags:
      - Fittings
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/characters/{character_id}/fleet/:
    get:
      description: |-
        Return the fleet ID the character is in, if any.

        ---

        This route is cached for up to 60 seconds

        SSO Scope: esi-fleets.read_fleet.v1
      operationId: get_characters_character_id_fleet
      security:
      - evesso:
        - esi-fleets.read_fleet.v1
      summary: Get character fleet info
      tags:
      - Fleets
      x-alternate-versions:
      - dev
      - legacy
      - v1
      - v2
      x-cached-seconds: 60
      x-accepts:
      - application/json
  /v1/characters/{character_id}/fw/stats/:
    get:
      description: |-
        Statistical overview of a character involved in faction warfare

        ---

        This route expires daily at 11:05

        SSO Scope: esi-characters.read_fw_stats.v1
      operationId: get_characters_character_id_fw_stats
      security:
      - evesso:
        - esi-characters.read_fw_stats.v1
      summary: Overview of a character involved in faction warfare
      tags:
      - Faction Warfare
      x-alternate-versions:
      - dev
      - legacy
      - v1
      - v2
      x-accepts:
      - application/json
  /v1/characters/{character_id}/implants/:
    get:
      description: |-
        Return implants on the active clone of a character

        ---

        This route is cached for up to 120 seconds

        SSO Scope: esi-clones.read_implants.v1
      operationId: get_characters_character_id_implants
      security:
      - evesso:
        - esi-clones.read_implants.v1
      summary: Get active implants
      tags:
      - Clones
      x-alternate-versions:
      - dev
      - legacy
      - v1
      - v2
      x-cached-seconds: 120
      x-accepts:
      - application/json
  /v1/characters/{character_id}/industry/jobs/:
    get:
      description: |-
        List industry jobs placed by a character

        ---

        This route is cached for up to 300 seconds

        SSO Scope: esi-industry.read_character_jobs.v1
      operationId: get_characters_character_id_industry_jobs
      security:
      - evesso:
        - esi-industry.read_character_jobs.v1
      summary: List character industry jobs
      tags:
      - Industry
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 300
      x-accepts:
      - application/json
  /v1/characters/{character_id}/killmails/recent/:
    get:
      description: |-
        Return a list of a character's kills and losses going back 90 days

        ---

        This route is cached for up to 300 seconds

        SSO Scope: esi-killmails.read_killmails.v1
      operationId: get_characters_character_id_killmails_recent
      security:
      - evesso:
        - esi-killmails.read_killmails.v1
      summary: Get a character's recent kills and losses
      tags:
      - Killmails
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 300
      x-accepts:
      - application/json
  /v1/characters/{character_id}/location/:
    get:
      description: |-
        Information about the characters current location. Returns the current solar system id, and also the current station or structure ID if applicable

        ---

        This route is cached for up to 5 seconds

        SSO Scope: esi-location.read_location.v1
      operationId: get_characters_character_id_location
      security:
      - evesso:
        - esi-location.read_location.v1
      summary: Get character location
      tags:
      - Location
      x-alternate-versions:
      - dev
      - legacy
      - v1
      - v2
      x-cached-seconds: 5
      x-accepts:
      - application/json
  /v1/characters/{character_id}/loyalty/points/:
    get:
      description: |-
        Return a list of loyalty points for all corporations the character has worked for

        ---

        This route is cached for up to 3600 seconds

        SSO Scope: esi-characters.read_loyalty.v1
      operationId: get_characters_character_id_loyalty_points
      security:
      - evesso:
        - esi-characters.read_loyalty.v1
      summary: Get loyalty points
      tags:
      - Loyalty
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v1/characters/{character_id}/mail/:
    get:
      description: |-
        Return the 50 most recent mail headers belonging to the character that match the query criteria. Queries can be filtered by label, and last_mail_id can be used to paginate backwards

        ---

        This route is cached for up to 30 seconds

        SSO Scope: esi-mail.read_mail.v1
      operationId: get_characters_character_id_mail
      security:
      - evesso:
        - esi-mail.read_mail.v1
      summary: Return mail headers
      tags:
      - Mail
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 30
      x-accepts:
      - application/json
    post:
      description: |-
        Create and send a new mail

        ---


        SSO Scope: esi-mail.send_mail.v1
      operationId: post_characters_character_id_mail
      security:
      - evesso:
        - esi-mail.send_mail.v1
      summary: Send a new mail
      tags:
      - Mail
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/characters/{character_id}/mail/labels/{label_id}/:
    delete:
      description: |-
        Delete a mail label

        ---


        SSO Scope: esi-mail.organize_mail.v1
      operationId: delete_characters_character_id_mail_labels_label_id
      security:
      - evesso:
        - esi-mail.organize_mail.v1
      summary: Delete a mail label
      tags:
      - Mail
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/characters/{character_id}/mail/lists/:
    get:
      description: |-
        Return all mailing lists that the character is subscribed to

        ---

        This route is cached for up to 120 seconds

        SSO Scope: esi-mail.read_mail.v1
      operationId: get_characters_character_id_mail_lists
      security:
      - evesso:
        - esi-mail.read_mail.v1
      summary: Return mailing list subscriptions
      tags:
      - Mail
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 120
      x-accepts:
      - application/json
  /v1/characters/{character_id}/mail/{mail_id}/:
    delete:
      description: |-
        Delete a mail

        ---


        SSO Scope: esi-mail.organize_mail.v1
      operationId: delete_characters_character_id_mail_mail_id
      security:
      - evesso:
        - esi-mail.organize_mail.v1
      summary: Delete a mail
      tags:
      - Mail
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-accepts:
      - application/json
    get:
      description: |-
        Return the contents of an EVE mail

        ---

        This route is cached for up to 30 seconds

        SSO Scope: esi-mail.read_mail.v1
      operationId: get_characters_character_id_mail_mail_id
      security:
      - evesso:
        - esi-mail.read_mail.v1
      summary: Return a mail
      tags:
      - Mail
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 30
      x-accepts:
      - application/json
    put:
      description: |-
        Update metadata about a mail

        ---


        SSO Scope: esi-mail.organize_mail.v1
      operationId: put_characters_character_id_mail_mail_id
      security:
      - evesso:
        - esi-mail.organize_mail.v1
      summary: Update metadata about a mail
      tags:
      - Mail
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/characters/{character_id}/mining/:
    get:
      description: |-
        Paginated record of all mining done by a character for the past 30 days

        ---

        This route is cached for up to 600 seconds

        SSO Scope: esi-industry.read_character_mining.v1
      operationId: get_characters_character_id_mining
      security:
      - evesso:
        - esi-industry.read_character_mining.v1
      summary: Character mining ledger
      tags:
      - Industry
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 600
      x-accepts:
      - application/json
  /v1/characters/{character_id}/orders/history/:
    get:
      description: |-
        List cancelled and expired market orders placed by a character up to 90 days in the past.

        ---

        This route is cached for up to 3600 seconds

        SSO Scope: esi-markets.read_character_orders.v1
      operationId: get_characters_character_id_orders_history
      security:
      - evesso:
        - esi-markets.read_character_orders.v1
      summary: List historical orders by a character
      tags:
      - Market
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v1/characters/{character_id}/planets/:
    get:
      description: |-
        Returns a list of all planetary colonies owned by a character.

        ---

        This route is cached for up to 600 seconds

        SSO Scope: esi-planets.manage_planets.v1
      operationId: get_characters_character_id_planets
      security:
      - evesso:
        - esi-planets.manage_planets.v1
      summary: Get colonies
      tags:
      - Planetary Interaction
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 600
      x-accepts:
      - application/json
  /v1/characters/{character_id}/ship/:
    get:
      description: |-
        Get the current ship type, name and id

        ---

        This route is cached for up to 5 seconds

        SSO Scope: esi-location.read_ship_type.v1
      operationId: get_characters_character_id_ship
      security:
      - evesso:
        - esi-location.read_ship_type.v1
      summary: Get current ship
      tags:
      - Location
      x-alternate-versions:
      - dev
      - legacy
      - v1
      - v2
      x-cached-seconds: 5
      x-accepts:
      - application/json
  /v1/characters/{character_id}/wallet/:
    get:
      description: |-
        Returns a character's wallet balance

        ---

        This route is cached for up to 120 seconds

        ---
        [Diff of the upcoming changes](https://esi.evetech.net/diff/latest/dev/#GET-/characters/{character_id}/wallet/)

        SSO Scope: esi-wallet.read_character_wallet.v1
      operationId: get_characters_character_id_wallet
      security:
      - evesso:
        - esi-wallet.read_character_wallet.v1
      summary: Get a character's wallet balance
      tags:
      - Wallet
      x-alternate-versions:
      - legacy
      - v1
      x-cached-seconds: 120
      x-accepts:
      - application/json
  /v1/characters/{character_id}/wallet/transactions/:
    get:
      description: |-
        Get wallet transactions of a character

        ---

        This route is cached for up to 3600 seconds

        SSO Scope: esi-wallet.read_character_wallet.v1
      operationId: get_characters_character_id_wallet_transactions
      security:
      - evesso:
        - esi-wallet.read_character_wallet.v1
      summary: Get wallet transactions
      tags:
      - Wallet
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v1/contracts/public/bids/{contract_id}/:
    get:
      description: |-
        Lists bids on a public auction contract

        ---

        This route is cached for up to 300 seconds
      operationId: get_contracts_public_bids_contract_id
      summary: Get public contract bids
      tags:
      - Contracts
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 300
      x-accepts:
      - application/json
  /v1/contracts/public/items/{contract_id}/:
    get:
      description: |-
        Lists items of a public contract

        ---

        This route is cached for up to 3600 seconds
      operationId: get_contracts_public_items_contract_id
      summary: Get public contract items
      tags:
      - Contracts
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v1/contracts/public/{region_id}/:
    get:
      description: |-
        Returns a paginated list of all public contracts in the given region

        ---

        This route is cached for up to 1800 seconds
      operationId: get_contracts_public_region_id
      summary: Get public contracts
      tags:
      - Contracts
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 1800
      x-accepts:
      - application/json
  /v1/corporation/{corporation_id}/mining/extractions/:
    get:
      description: |-
        Extraction timers for all moon chunks being extracted by refineries belonging to a corporation.

        ---

        This route is cached for up to 1800 seconds

        ---
        Requires one of the following EVE corporation role(s): Station_Manager

        SSO Scope: esi-industry.read_corporation_mining.v1
      operationId: get_corporation_corporation_id_mining_extractions
      security:
      - evesso:
        - esi-industry.read_corporation_mining.v1
      summary: Moon extraction timers
      tags:
      - Industry
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 1800
      x-required-roles:
      - Station_Manager
      x-accepts:
      - application/json
  /v1/corporation/{corporation_id}/mining/observers/:
    get:
      description: |-
        Paginated list of all entities capable of observing and recording mining for a corporation

        ---

        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Accountant

        SSO Scope: esi-industry.read_corporation_mining.v1
      operationId: get_corporation_corporation_id_mining_observers
      security:
      - evesso:
        - esi-industry.read_corporation_mining.v1
      summary: Corporation mining observers
      tags:
      - Industry
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 3600
      x-required-roles:
      - Accountant
      x-accepts:
      - application/json
  /v1/corporation/{corporation_id}/mining/observers/{observer_id}/:
    get:
      description: |-
        Paginated record of all mining seen by an observer

        ---

        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Accountant

        SSO Scope: esi-industry.read_corporation_mining.v1
      operationId: get_corporation_corporation_id_mining_observers_observer_id
      security:
      - evesso:
        - esi-industry.read_corporation_mining.v1
      summary: Observed corporation mining
      tags:
      - Industry
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 3600
      x-required-roles:
      - Accountant
      x-accepts:
      - application/json
  /v1/corporations/{corporation_id}/assets/names/:
    post:
      description: |-
        Return names for a set of item ids, which you can get from corporation assets endpoint. Only valid for items that can customize names, like containers or ships

        ---

        Requires one of the following EVE corporation role(s): Director

        SSO Scope: esi-assets.read_corporation_assets.v1
      operationId: post_corporations_corporation_id_assets_names
      security:
      - evesso:
        - esi-assets.read_corporation_assets.v1
      summary: Get corporation asset names
      tags:
      - Assets
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-required-roles:
      - Director
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/corporations/{corporation_id}/contacts/labels/:
    get:
      description: |-
        Return custom labels for a corporation's contacts

        ---

        This route is cached for up to 300 seconds

        SSO Scope: esi-corporations.read_contacts.v1
      operationId: get_corporations_corporation_id_contacts_labels
      security:
      - evesso:
        - esi-corporations.read_contacts.v1
      summary: Get corporation contact labels
      tags:
      - Contacts
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 300
      x-required-roles: []
      x-accepts:
      - application/json
  /v1/corporations/{corporation_id}/contracts/:
    get:
      description: |-
        Returns contracts available to a corporation, only if the corporation is issuer, acceptor or assignee. Only returns contracts no older than 30 days, or if the status is "in_progress".

        ---

        This route is cached for up to 300 seconds
      operationId: get_corporations_corporation_id_contracts
      security:
      - evesso:
        - esi-contracts.read_corporation_contracts.v1
      summary: Get corporation contracts
      tags:
      - Contracts
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 300
      x-required-roles: []
      x-accepts:
      - application/json
  /v1/corporations/{corporation_id}/contracts/{contract_id}/bids/:
    get:
      description: |-
        Lists bids on a particular auction contract

        ---

        This route is cached for up to 3600 seconds

        SSO Scope: esi-contracts.read_corporation_contracts.v1
      operationId: get_corporations_corporation_id_contracts_contract_id_bids
      security:
      - evesso:
        - esi-contracts.read_corporation_contracts.v1
      summary: Get corporation contract bids
      tags:
      - Contracts
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 3600
      x-required-roles: []
      x-accepts:
      - application/json
  /v1/corporations/{corporation_id}/contracts/{contract_id}/items/:
    get:
      description: |-
        Lists items of a particular contract

        ---

        This route is cached for up to 3600 seconds

        SSO Scope: esi-contracts.read_corporation_contracts.v1

        SSO Scope: esi-contracts.read_character_contracts.v1
      operationId: get_corporations_corporation_id_contracts_contract_id_items
      security:
      - evesso:
        - esi-contracts.read_corporation_contracts.v1
      summary: Get corporation contract items
      tags:
      - Contracts
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 3600
      x-required-roles: []
      x-accepts:
      - application/json
  /v1/corporations/{corporation_id}/customs_offices/:
    get:
      description: |-
        List customs offices owned by a corporation

        ---

        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director

        SSO Scope: esi-planets.read_customs_offices.v1
      operationId: get_corporations_corporation_id_customs_offices
      security:
      - evesso:
        - esi-planets.read_customs_offices.v1
      summary: List corporation customs offices
      tags:
      - Planetary Interaction
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 3600
      x-required-roles:
      - Director
      x-accepts:
      - application/json
  /v1/corporations/{corporation_id}/fw/stats/:
    get:
      description: |-
        Statistics about a corporation involved in faction warfare

        ---

        This route expires daily at 11:05

        SSO Scope: esi-corporations.read_fw_stats.v1
      operationId: get_corporations_corporation_id_fw_stats
      security:
      - evesso:
        - esi-corporations.read_fw_stats.v1
      summary: Overview of a corporation involved in faction warfare
      tags:
      - Faction Warfare
      x-alternate-versions:
      - dev
      - legacy
      - v1
      - v2
      x-accepts:
      - application/json
  /v1/corporations/{corporation_id}/icons/:
    get:
      description: |-
        Get the icon urls for a corporation

        ---

        This route is cached for up to 3600 seconds
      operationId: get_corporations_corporation_id_icons
      summary: Get corporation icon
      tags:
      - Corporation
      x-alternate-versions:
      - dev
      - legacy
      - v1
      - v2
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v1/corporations/{corporation_id}/industry/jobs/:
    get:
      description: |-
        List industry jobs run by a corporation

        ---

        This route is cached for up to 300 seconds

        ---
        Requires one of the following EVE corporation role(s): Factory_Manager

        SSO Scope: esi-industry.read_corporation_jobs.v1
      operationId: get_corporations_corporation_id_industry_jobs
      security:
      - evesso:
        - esi-industry.read_corporation_jobs.v1
      summary: List corporation industry jobs
      tags:
      - Industry
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 300
      x-required-roles:
      - Factory_Manager
      x-accepts:
      - application/json
  /v1/corporations/{corporation_id}/killmails/recent/:
    get:
      description: |-
        Get a list of a corporation's kills and losses going back 90 days

        ---

        This route is cached for up to 300 seconds

        ---
        Requires one of the following EVE corporation role(s): Director

        SSO Scope: esi-killmails.read_corporation_killmails.v1
      operationId: get_corporations_corporation_id_killmails_recent
      security:
      - evesso:
        - esi-killmails.read_corporation_killmails.v1
      summary: Get a corporation's recent kills and losses
      tags:
      - Killmails
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 300
      x-required-roles:
      - Director
      x-accepts:
      - application/json
  /v1/corporations/{corporation_id}/orders/history/:
    get:
      description: |-
        List cancelled and expired market orders placed on behalf of a corporation up to 90 days in the past.

        ---

        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Accountant, Trader

        SSO Scope: esi-markets.read_corporation_orders.v1
      operationId: get_corporations_corporation_id_orders_history
      security:
      - evesso:
        - esi-markets.read_corporation_orders.v1
      summary: List historical orders from a corporation
      tags:
      - Market
      x-alternate-versions:
      - dev
      - legacy
      - v1
      - v2
      x-cached-seconds: 3600
      x-required-roles:
      - Accountant
      - Trader
      x-accepts:
      - application/json
  /v1/corporations/{corporation_id}/shareholders/:
    get:
      description: |-
        Return the current shareholders of a corporation.

        ---

        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director

        SSO Scope: esi-wallet.read_corporation_wallets.v1
      operationId: get_corporations_corporation_id_shareholders
      security:
      - evesso:
        - esi-wallet.read_corporation_wallets.v1
      summary: Get corporation shareholders
      tags:
      - Corporation
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 3600
      x-required-roles:
      - Director
      x-accepts:
      - application/json
  /v1/corporations/{corporation_id}/wallets/:
    get:
      description: |-
        Get a corporation's wallets

        ---

        This route is cached for up to 300 seconds

        ---
        Requires one of the following EVE corporation role(s): Accountant, Junior_Accountant

        SSO Scope: esi-wallet.read_corporation_wallets.v1
      operationId: get_corporations_corporation_id_wallets
      security:
      - evesso:
        - esi-wallet.read_corporation_wallets.v1
      summary: Returns a corporation's wallet balance
      tags:
      - Wallet
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 300
      x-required-roles:
      - Accountant
      - Junior_Accountant
      x-accepts:
      - application/json
  /v1/corporations/{corporation_id}/wallets/{division}/transactions/:
    get:
      description: |-
        Get wallet transactions of a corporation

        ---

        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Accountant, Junior_Accountant

        SSO Scope: esi-wallet.read_corporation_wallets.v1
      operationId: get_corporations_corporation_id_wallets_division_transactions
      security:
      - evesso:
        - esi-wallet.read_corporation_wallets.v1
      summary: Get corporation wallet transactions
      tags:
      - Wallet
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 3600
      x-required-roles:
      - Accountant
      - Junior_Accountant
      x-accepts:
      - application/json
  /v1/dogma/attributes/:
    get:
      description: |-
        Get a list of dogma attribute ids

        ---

        This route expires daily at 11:05
      operationId: get_dogma_attributes
      summary: Get attributes
      tags:
      - Dogma
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/dogma/attributes/{attribute_id}/:
    get:
      description: |-
        Get information on a dogma attribute

        ---

        This route expires daily at 11:05
      operationId: get_dogma_attributes_attribute_id
      summary: Get attribute information
      tags:
      - Dogma
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/dogma/dynamic/items/{type_id}/{item_id}/:
    get:
      description: |-
        Returns info about a dynamic item resulting from mutation with a mutaplasmid.

        ---

        This route expires daily at 11:05
      operationId: get_dogma_dynamic_items_type_id_item_id
      summary: Get dynamic item information
      tags:
      - Dogma
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/dogma/effects/:
    get:
      description: |-
        Get a list of dogma effect ids

        ---

        This route expires daily at 11:05
      operationId: get_dogma_effects
      summary: Get effects
      tags:
      - Dogma
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/fleets/{fleet_id}/:
    get:
      description: |-
        Return details about a fleet

        ---

        This route is cached for up to 5 seconds

        SSO Scope: esi-fleets.read_fleet.v1
      operationId: get_fleets_fleet_id
      security:
      - evesso:
        - esi-fleets.read_fleet.v1
      summary: Get fleet information
      tags:
      - Fleets
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 5
      x-accepts:
      - application/json
    put:
      description: |-
        Update settings about a fleet

        ---


        SSO Scope: esi-fleets.write_fleet.v1
      operationId: put_fleets_fleet_id
      security:
      - evesso:
        - esi-fleets.write_fleet.v1
      summary: Update fleet
      tags:
      - Fleets
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/fleets/{fleet_id}/members/:
    get:
      description: |-
        Return information about fleet members

        ---

        This route is cached for up to 5 seconds

        SSO Scope: esi-fleets.read_fleet.v1
      operationId: get_fleets_fleet_id_members
      security:
      - evesso:
        - esi-fleets.read_fleet.v1
      summary: Get fleet members
      tags:
      - Fleets
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 5
      x-accepts:
      - application/json
    post:
      description: |-
        Invite a character into the fleet. If a character has a CSPA charge set it is not possible to invite them to the fleet using ESI

        ---


        SSO Scope: esi-fleets.write_fleet.v1
      operationId: post_fleets_fleet_id_members
      security:
      - evesso:
        - esi-fleets.write_fleet.v1
      summary: Create fleet invitation
      tags:
      - Fleets
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/fleets/{fleet_id}/members/{member_id}/:
    delete:
      description: |-
        Kick a fleet member

        ---


        SSO Scope: esi-fleets.write_fleet.v1
      operationId: delete_fleets_fleet_id_members_member_id
      security:
      - evesso:
        - esi-fleets.write_fleet.v1
      summary: Kick fleet member
      tags:
      - Fleets
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-accepts:
      - application/json
    put:
      description: |-
        Move a fleet member around

        ---


        SSO Scope: esi-fleets.write_fleet.v1
      operationId: put_fleets_fleet_id_members_member_id
      security:
      - evesso:
        - esi-fleets.write_fleet.v1
      summary: Move fleet member
      tags:
      - Fleets
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/fleets/{fleet_id}/squads/{squad_id}/:
    delete:
      description: |-
        Delete a fleet squad, only empty squads can be deleted

        ---


        SSO Scope: esi-fleets.write_fleet.v1
      operationId: delete_fleets_fleet_id_squads_squad_id
      security:
      - evesso:
        - esi-fleets.write_fleet.v1
      summary: Delete fleet squad
      tags:
      - Fleets
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-accepts:
      - application/json
    put:
      description: |-
        Rename a fleet squad

        ---


        SSO Scope: esi-fleets.write_fleet.v1
      operationId: put_fleets_fleet_id_squads_squad_id
      security:
      - evesso:
        - esi-fleets.write_fleet.v1
      summary: Rename fleet squad
      tags:
      - Fleets
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/fleets/{fleet_id}/wings/:
    get:
      description: |-
        Return information about wings in a fleet

        ---

        This route is cached for up to 5 seconds

        SSO Scope: esi-fleets.read_fleet.v1
      operationId: get_fleets_fleet_id_wings
      security:
      - evesso:
        - esi-fleets.read_fleet.v1
      summary: Get fleet wings
      tags:
      - Fleets
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 5
      x-accepts:
      - application/json
    post:
      description: |-
        Create a new wing in a fleet

        ---


        SSO Scope: esi-fleets.write_fleet.v1
      operationId: post_fleets_fleet_id_wings
      security:
      - evesso:
        - esi-fleets.write_fleet.v1
      summary: Create fleet wing
      tags:
      - Fleets
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/fleets/{fleet_id}/wings/{wing_id}/:
    delete:
      description: |-
        Delete a fleet wing, only empty wings can be deleted. The wing may contain squads, but the squads must be empty

        ---


        SSO Scope: esi-fleets.write_fleet.v1
      operationId: delete_fleets_fleet_id_wings_wing_id
      security:
      - evesso:
        - esi-fleets.write_fleet.v1
      summary: Delete fleet wing
      tags:
      - Fleets
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-accepts:
      - application/json
    put:
      description: |-
        Rename a fleet wing

        ---


        SSO Scope: esi-fleets.write_fleet.v1
      operationId: put_fleets_fleet_id_wings_wing_id
      security:
      - evesso:
        - esi-fleets.write_fleet.v1
      summary: Rename fleet wing
      tags:
      - Fleets
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/fleets/{fleet_id}/wings/{wing_id}/squads/:
    post:
      description: |-
        Create a new squad in a fleet

        ---


        SSO Scope: esi-fleets.write_fleet.v1
      operationId: post_fleets_fleet_id_wings_wing_id_squads
      security:
      - evesso:
        - esi-fleets.write_fleet.v1
      summary: Create fleet squad
      tags:
      - Fleets
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/fw/leaderboards/:
    get:
      description: |-
        Top 4 leaderboard of factions for kills and victory points separated by total, last week and yesterday

        ---

        This route expires daily at 11:05
      operationId: get_fw_leaderboards
      summary: List of the top factions in faction warfare
      tags:
      - Faction Warfare
      x-alternate-versions:
      - dev
      - legacy
      - v1
      - v2
      x-accepts:
      - application/json
  /v1/fw/leaderboards/characters/:
    get:
      description: |-
        Top 100 leaderboard of pilots for kills and victory points separated by total, last week and yesterday

        ---

        This route expires daily at 11:05
      operationId: get_fw_leaderboards_characters
      summary: List of the top pilots in faction warfare
      tags:
      - Faction Warfare
      x-alternate-versions:
      - dev
      - legacy
      - v1
      - v2
      x-accepts:
      - application/json
  /v1/fw/leaderboards/corporations/:
    get:
      description: |-
        Top 10 leaderboard of corporations for kills and victory points separated by total, last week and yesterday

        ---

        This route expires daily at 11:05
      operationId: get_fw_leaderboards_corporations
      summary: List of the top corporations in faction warfare
      tags:
      - Faction Warfare
      x-alternate-versions:
      - dev
      - legacy
      - v1
      - v2
      x-accepts:
      - application/json
  /v1/fw/stats/:
    get:
      description: |-
        Statistical overviews of factions involved in faction warfare

        ---

        This route expires daily at 11:05
      operationId: get_fw_stats
      summary: An overview of statistics about factions involved in faction warfare
      tags:
      - Faction Warfare
      x-alternate-versions:
      - dev
      - legacy
      - v1
      - v2
      x-accepts:
      - application/json
  /v1/fw/wars/:
    get:
      description: |-
        Data about which NPC factions are at war

        ---

        This route expires daily at 11:05
      operationId: get_fw_wars
      summary: Data about which NPC factions are at war
      tags:
      - Faction Warfare
      x-alternate-versions:
      - dev
      - legacy
      - v1
      - v2
      x-accepts:
      - application/json
  /v1/incursions/:
    get:
      description: |-
        Return a list of current incursions

        ---

        This route is cached for up to 300 seconds
      operationId: get_incursions
      summary: List incursions
      tags:
      - Incursions
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 300
      x-accepts:
      - application/json
  /v1/industry/facilities/:
    get:
      description: |-
        Return a list of industry facilities

        ---

        This route is cached for up to 3600 seconds
      operationId: get_industry_facilities
      summary: List industry facilities
      tags:
      - Industry
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v1/industry/systems/:
    get:
      description: |-
        Return cost indices for solar systems

        ---

        This route is cached for up to 3600 seconds
      operationId: get_industry_systems
      summary: List solar system cost indices
      tags:
      - Industry
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v1/insurance/prices/:
    get:
      description: |-
        Return available insurance levels for all ship types

        ---

        This route is cached for up to 3600 seconds
      operationId: get_insurance_prices
      summary: List insurance levels
      tags:
      - Insurance
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v1/killmails/{killmail_id}/{killmail_hash}/:
    get:
      description: |-
        Return a single killmail from its ID and hash

        ---

        This route is cached for up to 30758400 seconds
      operationId: get_killmails_killmail_id_killmail_hash
      summary: Get a single killmail
      tags:
      - Killmails
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 30758400
      x-accepts:
      - application/json
  /v1/loyalty/stores/{corporation_id}/offers/:
    get:
      description: |-
        Return a list of offers from a specific corporation's loyalty store

        ---

        This route expires daily at 11:05
      operationId: get_loyalty_stores_corporation_id_offers
      summary: List loyalty store offers
      tags:
      - Loyalty
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/markets/groups/:
    get:
      description: |-
        Get a list of item groups

        ---

        This route expires daily at 11:05
      operationId: get_markets_groups
      summary: Get item groups
      tags:
      - Market
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/markets/groups/{market_group_id}/:
    get:
      description: |-
        Get information on an item group

        ---

        This route expires daily at 11:05
      operationId: get_markets_groups_market_group_id
      summary: Get item group information
      tags:
      - Market
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/markets/prices/:
    get:
      description: |-
        Return a list of prices

        ---

        This route is cached for up to 3600 seconds
      operationId: get_markets_prices
      summary: List market prices
      tags:
      - Market
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v1/markets/structures/{structure_id}/:
    get:
      description: |-
        Return all orders in a structure

        ---

        This route is cached for up to 300 seconds

        SSO Scope: esi-markets.structure_markets.v1
      operationId: get_markets_structures_structure_id
      security:
      - evesso:
        - esi-markets.structure_markets.v1
      summary: List orders in a structure
      tags:
      - Market
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 300
      x-accepts:
      - application/json
  /v1/markets/{region_id}/history/:
    get:
      description: |-
        Return a list of historical market statistics for the specified type in a region

        ---

        This route expires daily at 11:05
      operationId: get_markets_region_id_history
      summary: List historical market statistics in a region
      tags:
      - Market
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/markets/{region_id}/orders/:
    get:
      description: |-
        Return a list of orders in a region

        ---

        This route is cached for up to 300 seconds
      operationId: get_markets_region_id_orders
      summary: List orders in a region
      tags:
      - Market
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 300
      x-accepts:
      - application/json
  /v1/markets/{region_id}/types/:
    get:
      description: |-
        Return a list of type IDs that have active orders in the region, for efficient market indexing.

        ---

        This route is cached for up to 600 seconds
      operationId: get_markets_region_id_types
      summary: List type IDs relevant to a market
      tags:
      - Market
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 600
      x-accepts:
      - application/json
  /v1/route/{origin}/{destination}/:
    get:
      description: |-
        Get the systems between origin and destination

        ---

        This route is cached for up to 86400 seconds
      operationId: get_route_origin_destination
      summary: Get route
      tags:
      - Routes
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 86400
      x-accepts:
      - application/json
  /v1/sovereignty/campaigns/:
    get:
      description: |-
        Shows sovereignty data for campaigns.

        ---

        This route is cached for up to 5 seconds
      operationId: get_sovereignty_campaigns
      summary: List sovereignty campaigns
      tags:
      - Sovereignty
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 5
      x-accepts:
      - application/json
  /v1/sovereignty/map/:
    get:
      description: |-
        Shows sovereignty information for solar systems

        ---

        This route is cached for up to 3600 seconds
      operationId: get_sovereignty_map
      summary: List sovereignty of systems
      tags:
      - Sovereignty
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v1/sovereignty/structures/:
    get:
      description: |-
        Shows sovereignty data for structures.

        ---

        This route is cached for up to 120 seconds
      operationId: get_sovereignty_structures
      summary: List sovereignty structures
      tags:
      - Sovereignty
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 120
      x-accepts:
      - application/json
  /v1/status/:
    get:
      description: |-
        EVE Server status

        ---

        This route is cached for up to 30 seconds
      operationId: get_status
      summary: Retrieve the uptime and player counts
      tags:
      - Status
      x-alternate-versions:
      - dev
      - legacy
      - v1
      - v2
      x-cached-seconds: 30
      x-accepts:
      - application/json
  /v1/ui/openwindow/contract/:
    post:
      description: |-
        Open the contract window inside the client

        ---


        SSO Scope: esi-ui.open_window.v1
      operationId: post_ui_openwindow_contract
      security:
      - evesso:
        - esi-ui.open_window.v1
      summary: Open Contract Window
      tags:
      - User Interface
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/ui/openwindow/information/:
    post:
      description: |-
        Open the information window for a character, corporation or alliance inside the client

        ---


        SSO Scope: esi-ui.open_window.v1
      operationId: post_ui_openwindow_information
      security:
      - evesso:
        - esi-ui.open_window.v1
      summary: Open Information Window
      tags:
      - User Interface
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/ui/openwindow/marketdetails/:
    post:
      description: |-
        Open the market details window for a specific typeID inside the client

        ---


        SSO Scope: esi-ui.open_window.v1
      operationId: post_ui_openwindow_marketdetails
      security:
      - evesso:
        - esi-ui.open_window.v1
      summary: Open Market Details
      tags:
      - User Interface
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/ui/openwindow/newmail/:
    post:
      description: |-
        Open the New Mail window, according to settings from the request if applicable

        ---


        SSO Scope: esi-ui.open_window.v1
      operationId: post_ui_openwindow_newmail
      security:
      - evesso:
        - esi-ui.open_window.v1
      summary: Open New Mail Window
      tags:
      - User Interface
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/universe/ancestries/:
    get:
      description: |-
        Get all character ancestries

        ---

        This route expires daily at 11:05
      operationId: get_universe_ancestries
      summary: Get ancestries
      tags:
      - Universe
      x-alternate-versions:
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/universe/asteroid_belts/{asteroid_belt_id}/:
    get:
      description: |-
        Get information on an asteroid belt

        ---

        This route expires daily at 11:05
      operationId: get_universe_asteroid_belts_asteroid_belt_id
      summary: Get asteroid belt information
      tags:
      - Universe
      x-alternate-versions:
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/universe/bloodlines/:
    get:
      description: |-
        Get a list of bloodlines

        ---

        This route expires daily at 11:05
      operationId: get_universe_bloodlines
      summary: Get bloodlines
      tags:
      - Universe
      x-alternate-versions:
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/universe/categories/:
    get:
      description: |-
        Get a list of item categories

        ---

        This route expires daily at 11:05
      operationId: get_universe_categories
      summary: Get item categories
      tags:
      - Universe
      x-alternate-versions:
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/universe/categories/{category_id}/:
    get:
      description: |-
        Get information of an item category

        ---

        This route expires daily at 11:05
      operationId: get_universe_categories_category_id
      summary: Get item category information
      tags:
      - Universe
      x-alternate-versions:
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/universe/constellations/:
    get:
      description: |-
        Get a list of constellations

        ---

        This route expires daily at 11:05
      operationId: get_universe_constellations
      summary: Get constellations
      tags:
      - Universe
      x-alternate-versions:
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/universe/constellations/{constellation_id}/:
    get:
      description: |-
        Get information on a constellation

        ---

        This route expires daily at 11:05
      operationId: get_universe_constellations_constellation_id
      summary: Get constellation information
      tags:
      - Universe
      x-alternate-versions:
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/universe/graphics/:
    get:
      description: |-
        Get a list of graphics

        ---

        This route expires daily at 11:05
      operationId: get_universe_graphics
      summary: Get graphics
      tags:
      - Universe
      x-alternate-versions:
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/universe/graphics/{graphic_id}/:
    get:
      description: |-
        Get information on a graphic

        ---

        This route expires daily at 11:05
      operationId: get_universe_graphics_graphic_id
      summary: Get graphic information
      tags:
      - Universe
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/universe/groups/:
    get:
      description: |-
        Get a list of item groups

        ---

        This route expires daily at 11:05
      operationId: get_universe_groups
      summary: Get item groups
      tags:
      - Universe
      x-alternate-versions:
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/universe/groups/{group_id}/:
    get:
      description: |-
        Get information on an item group

        ---

        This route expires daily at 11:05
      operationId: get_universe_groups_group_id
      summary: Get item group information
      tags:
      - Universe
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/universe/ids/:
    post:
      description: |
        Resolve a set of names to IDs in the following categories: agents, alliances, characters, constellations, corporations factions, inventory_types, regions, stations, and systems. Only exact matches will be returned. All names searched for are cached for 12 hours

        ---
      operationId: post_universe_ids
      summary: Bulk names to IDs
      tags:
      - Universe
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/universe/moons/{moon_id}/:
    get:
      description: |-
        Get information on a moon

        ---

        This route expires daily at 11:05
      operationId: get_universe_moons_moon_id
      summary: Get moon information
      tags:
      - Universe
      x-alternate-versions:
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/universe/planets/{planet_id}/:
    get:
      description: |-
        Get information on a planet

        ---

        This route expires daily at 11:05
      operationId: get_universe_planets_planet_id
      summary: Get planet information
      tags:
      - Universe
      x-alternate-versions:
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/universe/races/:
    get:
      description: |-
        Get a list of character races

        ---

        This route expires daily at 11:05
      operationId: get_universe_races
      summary: Get character races
      tags:
      - Universe
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/universe/regions/:
    get:
      description: |-
        Get a list of regions

        ---

        This route expires daily at 11:05
      operationId: get_universe_regions
      summary: Get regions
      tags:
      - Universe
      x-alternate-versions:
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/universe/regions/{region_id}/:
    get:
      description: |-
        Get information on a region

        ---

        This route expires daily at 11:05
      operationId: get_universe_regions_region_id
      summary: Get region information
      tags:
      - Universe
      x-alternate-versions:
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/universe/schematics/{schematic_id}/:
    get:
      description: |-
        Get information on a planetary factory schematic

        ---

        This route is cached for up to 3600 seconds
      operationId: get_universe_schematics_schematic_id
      summary: Get schematic information
      tags:
      - Planetary Interaction
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v1/universe/stargates/{stargate_id}/:
    get:
      description: |-
        Get information on a stargate

        ---

        This route expires daily at 11:05
      operationId: get_universe_stargates_stargate_id
      summary: Get stargate information
      tags:
      - Universe
      x-alternate-versions:
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/universe/stars/{star_id}/:
    get:
      description: |-
        Get information on a star

        ---

        This route expires daily at 11:05
      operationId: get_universe_stars_star_id
      summary: Get star information
      tags:
      - Universe
      x-alternate-versions:
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/universe/structures/:
    get:
      description: |-
        List all public structures

        ---

        This route is cached for up to 3600 seconds
      operationId: get_universe_structures
      summary: List all public structures
      tags:
      - Universe
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v1/universe/structures/{structure_id}/:
    get:
      description: |-
        Returns information on requested structure if you are on the ACL. Otherwise, returns "Forbidden" for all inputs.

        ---

        This route is cached for up to 3600 seconds
      operationId: get_universe_structures_structure_id
      security:
      - evesso:
        - esi-universe.read_structures.v1
      summary: Get structure information
      tags:
      - Universe
      x-alternate-versions:
      - legacy
      - v1
      - v2
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v1/universe/system_jumps/:
    get:
      description: |-
        Get the number of jumps in solar systems within the last hour ending at the timestamp of the Last-Modified header, excluding wormhole space. Only systems with jumps will be listed

        ---

        This route is cached for up to 3600 seconds
      operationId: get_universe_system_jumps
      summary: Get system jumps
      tags:
      - Universe
      x-alternate-versions:
      - legacy
      - v1
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v1/universe/systems/:
    get:
      description: |-
        Get a list of solar systems

        ---

        This route expires daily at 11:05
      operationId: get_universe_systems
      summary: Get solar systems
      tags:
      - Universe
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/universe/types/:
    get:
      description: |-
        Get a list of type ids

        ---

        This route expires daily at 11:05
      operationId: get_universe_types
      summary: Get types
      tags:
      - Universe
      x-alternate-versions:
      - legacy
      - v1
      x-accepts:
      - application/json
  /v1/wars/:
    get:
      description: |-
        Return a list of wars

        ---

        This route is cached for up to 3600 seconds
      operationId: get_wars
      summary: List wars
      tags:
      - Wars
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v1/wars/{war_id}/:
    get:
      description: |-
        Return details about a war

        ---

        This route is cached for up to 3600 seconds
      operationId: get_wars_war_id
      summary: Get war information
      tags:
      - Wars
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v1/wars/{war_id}/killmails/:
    get:
      description: |-
        Return a list of kills related to a war

        ---

        This route is cached for up to 3600 seconds
      operationId: get_wars_war_id_killmails
      summary: List kills for a war
      tags:
      - Wars
      x-alternate-versions:
      - dev
      - legacy
      - v1
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v2/alliances/{alliance_id}/contacts/:
    get:
      description: |-
        Return contacts of an alliance

        ---

        This route is cached for up to 300 seconds

        SSO Scope: esi-alliances.read_contacts.v1
      operationId: get_alliances_alliance_id_contacts
      security:
      - evesso:
        - esi-alliances.read_contacts.v1
      summary: Get alliance contacts
      tags:
      - Contacts
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 300
      x-accepts:
      - application/json
  /v2/characters/{character_id}/agents_research/:
    get:
      description: |-
        Return a list of agents research information for a character. The formula for finding the current research points with an agent is: currentPoints = remainderPoints + pointsPerDay * days(currentTime - researchStartDate)

        ---

        This route is cached for up to 3600 seconds

        SSO Scope: esi-characters.read_agents_research.v1
      operationId: get_characters_character_id_agents_research
      security:
      - evesso:
        - esi-characters.read_agents_research.v1
      summary: Get agents research
      tags:
      - Character
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v2/characters/{character_id}/assets/locations/:
    post:
      description: |-
        Return locations for a set of item ids, which you can get from character assets endpoint. Coordinates for items in hangars or stations are set to (0,0,0)

        ---


        SSO Scope: esi-assets.read_assets.v1
      operationId: post_characters_character_id_assets_locations
      security:
      - evesso:
        - esi-assets.read_assets.v1
      summary: Get character asset locations
      tags:
      - Assets
      x-alternate-versions:
      - dev
      - v2
      x-content-type: application/json
      x-accepts:
      - application/json
  /v2/characters/{character_id}/clones/:
    get:
      description: |-
        A list of the character's clones

        ---

        This route is cached for up to 120 seconds

        SSO Scope: esi-clones.read_clones.v1
      operationId: get_characters_character_id_clones
      security:
      - evesso:
        - esi-clones.read_clones.v1
      summary: Get clones
      tags:
      - Clones
      x-alternate-versions:
      - dev
      - legacy
      - v2
      - v3
      - v4
      x-cached-seconds: 120
      x-accepts:
      - application/json
  /v2/characters/{character_id}/contacts/:
    get:
      description: |-
        Return contacts of a character

        ---

        This route is cached for up to 300 seconds

        SSO Scope: esi-characters.read_contacts.v1
      operationId: get_characters_character_id_contacts
      security:
      - evesso:
        - esi-characters.read_contacts.v1
      summary: Get contacts
      tags:
      - Contacts
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 300
      x-accepts:
      - application/json
    post:
      description: |-
        Bulk add contacts with same settings

        ---


        SSO Scope: esi-characters.write_contacts.v1
      operationId: post_characters_character_id_contacts
      security:
      - evesso:
        - esi-characters.write_contacts.v1
      summary: Add contacts
      tags:
      - Contacts
      x-alternate-versions:
      - dev
      - v2
      x-content-type: application/json
      x-accepts:
      - application/json
    put:
      description: |-
        Bulk edit contacts with same settings

        ---


        SSO Scope: esi-characters.write_contacts.v1
      operationId: put_characters_character_id_contacts
      security:
      - evesso:
        - esi-characters.write_contacts.v1
      summary: Edit contacts
      tags:
      - Contacts
      x-alternate-versions:
      - dev
      - v2
      x-content-type: application/json
      x-accepts:
      - application/json
  /v2/characters/{character_id}/corporationhistory/:
    get:
      description: |-
        Get a list of all the corporations a character has been a member of

        ---

        This route is cached for up to 86400 seconds
      operationId: get_characters_character_id_corporationhistory
      summary: Get corporation history
      tags:
      - Character
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 86400
      x-accepts:
      - application/json
  /v2/characters/{character_id}/fatigue/:
    get:
      description: |-
        Return a character's jump activation and fatigue information

        ---

        This route is cached for up to 300 seconds

        SSO Scope: esi-characters.read_fatigue.v1
      operationId: get_characters_character_id_fatigue
      security:
      - evesso:
        - esi-characters.read_fatigue.v1
      summary: Get jump fatigue
      tags:
      - Character
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 300
      x-accepts:
      - application/json
  /v2/characters/{character_id}/fittings/:
    get:
      description: |-
        Return fittings of a character

        ---

        This route is cached for up to 300 seconds

        SSO Scope: esi-fittings.read_fittings.v1
      operationId: get_characters_character_id_fittings
      security:
      - evesso:
        - esi-fittings.read_fittings.v1
      summary: Get fittings
      tags:
      - Fittings
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 300
      x-accepts:
      - application/json
  /v2/characters/{character_id}/mail/labels/:
    post:
      description: |-
        Create a mail label

        ---


        SSO Scope: esi-mail.organize_mail.v1
      operationId: post_characters_character_id_mail_labels
      security:
      - evesso:
        - esi-mail.organize_mail.v1
      summary: Create a mail label
      tags:
      - Mail
      x-alternate-versions:
      - dev
      - legacy
      - v2
      x-content-type: application/json
      x-accepts:
      - application/json
  /v2/characters/{character_id}/medals/:
    get:
      description: |-
        Return a list of medals the character has

        ---

        This route is cached for up to 3600 seconds

        SSO Scope: esi-characters.read_medals.v1
      operationId: get_characters_character_id_medals
      security:
      - evesso:
        - esi-characters.read_medals.v1
      summary: Get medals
      tags:
      - Character
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v2/characters/{character_id}/notifications/contacts/:
    get:
      description: |-
        Return notifications about having been added to someone's contact list

        ---

        This route is cached for up to 600 seconds

        SSO Scope: esi-characters.read_notifications.v1
      operationId: get_characters_character_id_notifications_contacts
      security:
      - evesso:
        - esi-characters.read_notifications.v1
      summary: Get new contact notifications
      tags:
      - Character
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 600
      x-accepts:
      - application/json
  /v2/characters/{character_id}/online/:
    get:
      description: |-
        Checks if the character is currently online

        ---

        This route is cached for up to 60 seconds

        SSO Scope: esi-location.read_online.v1
      operationId: get_characters_character_id_online
      security:
      - evesso:
        - esi-location.read_online.v1
      summary: Get character online
      tags:
      - Location
      x-alternate-versions:
      - dev
      - v2
      - v3
      x-cached-seconds: 60
      x-accepts:
      - application/json
  /v2/characters/{character_id}/orders/:
    get:
      description: |-
        List open market orders placed by a character

        ---

        This route is cached for up to 1200 seconds

        SSO Scope: esi-markets.read_character_orders.v1
      operationId: get_characters_character_id_orders
      security:
      - evesso:
        - esi-markets.read_character_orders.v1
      summary: List open orders from a character
      tags:
      - Market
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 1200
      x-accepts:
      - application/json
  /v2/characters/{character_id}/portrait/:
    get:
      description: |-
        Get portrait urls for a character

        ---

        This route expires daily at 11:05
      operationId: get_characters_character_id_portrait
      summary: Get character portraits
      tags:
      - Character
      x-alternate-versions:
      - dev
      - v2
      - v3
      x-accepts:
      - application/json
  /v2/characters/{character_id}/skillqueue/:
    get:
      description: |-
        List the configured skill queue for the given character

        ---

        This route is cached for up to 120 seconds

        SSO Scope: esi-skills.read_skillqueue.v1
      operationId: get_characters_character_id_skillqueue
      security:
      - evesso:
        - esi-skills.read_skillqueue.v1
      summary: Get character's skill queue
      tags:
      - Skills
      x-alternate-versions:
      - dev
      - legacy
      - v2
      x-cached-seconds: 120
      x-accepts:
      - application/json
  /v2/characters/{character_id}/standings/:
    get:
      description: |-
        Return character standings from agents, NPC corporations, and factions

        ---

        This route is cached for up to 3600 seconds

        SSO Scope: esi-characters.read_standings.v1
      operationId: get_characters_character_id_standings
      security:
      - evesso:
        - esi-characters.read_standings.v1
      summary: Get standings
      tags:
      - Character
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v2/characters/{character_id}/titles/:
    get:
      description: |-
        Returns a character's titles

        ---

        This route is cached for up to 3600 seconds

        SSO Scope: esi-characters.read_titles.v1
      operationId: get_characters_character_id_titles
      security:
      - evesso:
        - esi-characters.read_titles.v1
      summary: Get character corporation titles
      tags:
      - Character
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v2/corporations/npccorps/:
    get:
      description: |-
        Get a list of npc corporations

        ---

        This route expires daily at 11:05
      operationId: get_corporations_npccorps
      summary: Get npc corporations
      tags:
      - Corporation
      x-alternate-versions:
      - dev
      - v2
      x-accepts:
      - application/json
  /v2/corporations/{corporation_id}/assets/locations/:
    post:
      description: |-
        Return locations for a set of item ids, which you can get from corporation assets endpoint. Coordinates for items in hangars or stations are set to (0,0,0)

        ---

        Requires one of the following EVE corporation role(s): Director

        SSO Scope: esi-assets.read_corporation_assets.v1
      operationId: post_corporations_corporation_id_assets_locations
      security:
      - evesso:
        - esi-assets.read_corporation_assets.v1
      summary: Get corporation asset locations
      tags:
      - Assets
      x-alternate-versions:
      - dev
      - v2
      x-required-roles:
      - Director
      x-content-type: application/json
      x-accepts:
      - application/json
  /v2/corporations/{corporation_id}/contacts/:
    get:
      description: |-
        Return contacts of a corporation

        ---

        This route is cached for up to 300 seconds

        SSO Scope: esi-corporations.read_contacts.v1
      operationId: get_corporations_corporation_id_contacts
      security:
      - evesso:
        - esi-corporations.read_contacts.v1
      summary: Get corporation contacts
      tags:
      - Contacts
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 300
      x-required-roles: []
      x-accepts:
      - application/json
  /v2/corporations/{corporation_id}/divisions/:
    get:
      description: |-
        Return corporation hangar and wallet division names, only show if a division is not using the default name

        ---

        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director

        SSO Scope: esi-corporations.read_divisions.v1
      operationId: get_corporations_corporation_id_divisions
      security:
      - evesso:
        - esi-corporations.read_divisions.v1
      summary: Get corporation divisions
      tags:
      - Corporation
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 3600
      x-required-roles:
      - Director
      x-accepts:
      - application/json
  /v2/corporations/{corporation_id}/facilities/:
    get:
      description: |-
        Return a corporation's facilities

        ---

        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Factory_Manager

        SSO Scope: esi-corporations.read_facilities.v1
      operationId: get_corporations_corporation_id_facilities
      security:
      - evesso:
        - esi-corporations.read_facilities.v1
      summary: Get corporation facilities
      tags:
      - Corporation
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 3600
      x-required-roles:
      - Factory_Manager
      x-accepts:
      - application/json
  /v2/corporations/{corporation_id}/medals/:
    get:
      description: |-
        Returns a corporation's medals

        ---

        This route is cached for up to 3600 seconds

        SSO Scope: esi-corporations.read_medals.v1
      operationId: get_corporations_corporation_id_medals
      security:
      - evesso:
        - esi-corporations.read_medals.v1
      summary: Get corporation medals
      tags:
      - Corporation
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 3600
      x-required-roles: []
      x-accepts:
      - application/json
  /v2/corporations/{corporation_id}/medals/issued/:
    get:
      description: |-
        Returns medals issued by a corporation

        ---

        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director

        SSO Scope: esi-corporations.read_medals.v1
      operationId: get_corporations_corporation_id_medals_issued
      security:
      - evesso:
        - esi-corporations.read_medals.v1
      summary: Get corporation issued medals
      tags:
      - Corporation
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 3600
      x-required-roles:
      - Director
      x-accepts:
      - application/json
  /v2/corporations/{corporation_id}/members/limit/:
    get:
      description: |-
        Return a corporation's member limit, not including CEO himself

        ---

        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director

        SSO Scope: esi-corporations.track_members.v1
      operationId: get_corporations_corporation_id_members_limit
      security:
      - evesso:
        - esi-corporations.track_members.v1
      summary: Get corporation member limit
      tags:
      - Corporation
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 3600
      x-required-roles:
      - Director
      x-accepts:
      - application/json
  /v2/corporations/{corporation_id}/members/titles/:
    get:
      description: |-
        Returns a corporation's members' titles

        ---

        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director

        SSO Scope: esi-corporations.read_titles.v1
      operationId: get_corporations_corporation_id_members_titles
      security:
      - evesso:
        - esi-corporations.read_titles.v1
      summary: Get corporation's members' titles
      tags:
      - Corporation
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 3600
      x-required-roles:
      - Director
      x-accepts:
      - application/json
  /v2/corporations/{corporation_id}/membertracking/:
    get:
      description: |-
        Returns additional information about a corporation's members which helps tracking their activities

        ---

        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director

        SSO Scope: esi-corporations.track_members.v1
      operationId: get_corporations_corporation_id_membertracking
      security:
      - evesso:
        - esi-corporations.track_members.v1
      summary: Track corporation members
      tags:
      - Corporation
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 3600
      x-required-roles:
      - Director
      x-accepts:
      - application/json
  /v2/corporations/{corporation_id}/orders/:
    get:
      description: |-
        List open market orders placed on behalf of a corporation

        ---

        This route is cached for up to 1200 seconds

        ---
        Requires one of the following EVE corporation role(s): Accountant, Trader

        SSO Scope: esi-markets.read_corporation_orders.v1
      operationId: get_corporations_corporation_id_orders
      security:
      - evesso:
        - esi-markets.read_corporation_orders.v1
      summary: List open orders from a corporation
      tags:
      - Market
      x-alternate-versions:
      - dev
      - legacy
      - v2
      - v3
      x-cached-seconds: 1200
      x-required-roles:
      - Accountant
      - Trader
      x-accepts:
      - application/json
  /v2/corporations/{corporation_id}/roles/:
    get:
      description: |-
        Return the roles of all members if the character has the personnel manager role or any grantable role.

        ---

        This route is cached for up to 3600 seconds

        SSO Scope: esi-corporations.read_corporation_membership.v1
      operationId: get_corporations_corporation_id_roles
      security:
      - evesso:
        - esi-corporations.read_corporation_membership.v1
      summary: Get corporation member roles
      tags:
      - Corporation
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v2/corporations/{corporation_id}/roles/history/:
    get:
      description: |-
        Return how roles have changed for a coporation's members, up to a month

        ---

        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director

        SSO Scope: esi-corporations.read_corporation_membership.v1
      operationId: get_corporations_corporation_id_roles_history
      security:
      - evesso:
        - esi-corporations.read_corporation_membership.v1
      summary: Get corporation member roles history
      tags:
      - Corporation
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 3600
      x-required-roles:
      - Director
      x-accepts:
      - application/json
  /v2/corporations/{corporation_id}/standings/:
    get:
      description: |-
        Return corporation standings from agents, NPC corporations, and factions

        ---

        This route is cached for up to 3600 seconds

        SSO Scope: esi-corporations.read_standings.v1
      operationId: get_corporations_corporation_id_standings
      security:
      - evesso:
        - esi-corporations.read_standings.v1
      summary: Get corporation standings
      tags:
      - Corporation
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 3600
      x-required-roles: []
      x-accepts:
      - application/json
  /v2/corporations/{corporation_id}/starbases/:
    get:
      description: |-
        Returns list of corporation starbases (POSes)

        ---

        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director

        SSO Scope: esi-corporations.read_starbases.v1
      operationId: get_corporations_corporation_id_starbases
      security:
      - evesso:
        - esi-corporations.read_starbases.v1
      summary: Get corporation starbases (POSes)
      tags:
      - Corporation
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 3600
      x-required-roles:
      - Director
      x-accepts:
      - application/json
  /v2/corporations/{corporation_id}/starbases/{starbase_id}/:
    get:
      description: |-
        Returns various settings and fuels of a starbase (POS)

        ---

        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director

        SSO Scope: esi-corporations.read_starbases.v1
      operationId: get_corporations_corporation_id_starbases_starbase_id
      security:
      - evesso:
        - esi-corporations.read_starbases.v1
      summary: Get starbase (POS) detail
      tags:
      - Corporation
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 3600
      x-required-roles:
      - Director
      x-accepts:
      - application/json
  /v2/corporations/{corporation_id}/titles/:
    get:
      description: |-
        Returns a corporation's titles

        ---

        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director

        SSO Scope: esi-corporations.read_titles.v1
      operationId: get_corporations_corporation_id_titles
      security:
      - evesso:
        - esi-corporations.read_titles.v1
      summary: Get corporation titles
      tags:
      - Corporation
      x-alternate-versions:
      - dev
      - v2
      x-cached-seconds: 3600
      x-required-roles:
      - Director
      x-accepts:
      - application/json
  /v2/dogma/effects/{effect_id}/:
    get:
      description: |-
        Get information on a dogma effect

        ---

        This route expires daily at 11:05
      operationId: get_dogma_effects_effect_id
      summary: Get effect information
      tags:
      - Dogma
      x-alternate-versions:
      - dev
      - v2
      x-accepts:
      - application/json
  /v2/fw/systems/:
    get:
      description: |-
        An overview of the current ownership of faction warfare solar systems

        ---

        This route is cached for up to 1800 seconds
      operationId: get_fw_systems
      summary: Ownership of faction warfare systems
      tags:
      - Faction Warfare
      x-alternate-versions:
      - dev
      - legacy
      - v2
      - v3
      x-cached-seconds: 1800
      x-accepts:
      - application/json
  /v2/ui/autopilot/waypoint/:
    post:
      description: |-
        Set a solar system as autopilot waypoint

        ---


        SSO Scope: esi-ui.write_waypoint.v1
      operationId: post_ui_autopilot_waypoint
      security:
      - evesso:
        - esi-ui.write_waypoint.v1
      summary: Set Autopilot Waypoint
      tags:
      - User Interface
      x-alternate-versions:
      - dev
      - legacy
      - v2
      x-accepts:
      - application/json
  /v2/universe/factions/:
    get:
      description: |-
        Get a list of factions

        ---

        This route expires daily at 11:05
      operationId: get_universe_factions
      summary: Get factions
      tags:
      - Universe
      x-alternate-versions:
      - dev
      - v2
      x-accepts:
      - application/json
  /v2/universe/names/:
    post:
      description: |
        Resolve a set of IDs to names and categories. Supported ID's for resolving are: Characters, Corporations, Alliances, Stations, Solar Systems, Constellations, Regions, Types, Factions

        ---
      operationId: post_universe_names
      summary: Get names and categories for a set of IDs
      tags:
      - Universe
      x-alternate-versions:
      - dev
      - legacy
      - v2
      - v3
      x-content-type: application/json
      x-accepts:
      - application/json
  /v2/universe/stations/{station_id}/:
    get:
      description: |-
        Get information on a station

        ---

        This route expires daily at 11:05
      operationId: get_universe_stations_station_id
      summary: Get station information
      tags:
      - Universe
      x-alternate-versions:
      - dev
      - v2
      x-accepts:
      - application/json
  /v2/universe/system_kills/:
    get:
      description: |-
        Get the number of ship, pod and NPC kills per solar system within the last hour ending at the timestamp of the Last-Modified header, excluding wormhole space. Only systems with kills will be listed

        ---

        This route is cached for up to 3600 seconds
      operationId: get_universe_system_kills
      summary: Get system kills
      tags:
      - Universe
      x-alternate-versions:
      - v2
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v2/universe/types/{type_id}/:
    get:
      description: |-
        Get information on a type

        ---

        This route expires daily at 11:05
      operationId: get_universe_types_type_id
      summary: Get type information
      tags:
      - Universe
      x-alternate-versions:
      - dev
      - legacy
      - v2
      - v3
      x-accepts:
      - application/json
  /v3/alliances/{alliance_id}/:
    get:
      description: |-
        Public information about an alliance

        ---

        This route is cached for up to 3600 seconds
      operationId: get_alliances_alliance_id
      summary: Get alliance information
      tags:
      - Alliance
      x-alternate-versions:
      - dev
      - legacy
      - v3
      - v4
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v3/characters/{character_id}/blueprints/:
    get:
      description: |-
        Return a list of blueprints the character owns

        ---

        This route is cached for up to 3600 seconds

        SSO Scope: esi-characters.read_blueprints.v1
      operationId: get_characters_character_id_blueprints
      security:
      - evesso:
        - esi-characters.read_blueprints.v1
      summary: Get blueprints
      tags:
      - Character
      x-alternate-versions:
      - dev
      - v3
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v3/characters/{character_id}/calendar/{event_id}/:
    get:
      description: |-
        Get all the information for a specific event

        ---

        This route is cached for up to 5 seconds

        SSO Scope: esi-calendar.read_calendar_events.v1
      operationId: get_characters_character_id_calendar_event_id
      security:
      - evesso:
        - esi-calendar.read_calendar_events.v1
      summary: Get an event
      tags:
      - Calendar
      x-alternate-versions:
      - dev
      - legacy
      - v3
      - v4
      x-cached-seconds: 5
      x-accepts:
      - application/json
    put:
      description: |-
        Set your response status to an event

        ---

        This route is cached for up to 5 seconds

        SSO Scope: esi-calendar.respond_calendar_events.v1
      operationId: put_characters_character_id_calendar_event_id
      security:
      - evesso:
        - esi-calendar.respond_calendar_events.v1
      summary: Respond to an event
      tags:
      - Calendar
      x-alternate-versions:
      - dev
      - legacy
      - v3
      - v4
      x-cached-seconds: 5
      x-content-type: application/json
      x-accepts:
      - application/json
  /v3/characters/{character_id}/mail/labels/:
    get:
      description: |-
        Return a list of the users mail labels, unread counts for each label and a total unread count.

        ---

        This route is cached for up to 30 seconds

        SSO Scope: esi-mail.read_mail.v1
      operationId: get_characters_character_id_mail_labels
      security:
      - evesso:
        - esi-mail.read_mail.v1
      summary: Get mail labels and unread counts
      tags:
      - Mail
      x-alternate-versions:
      - dev
      - v3
      x-cached-seconds: 30
      x-accepts:
      - application/json
  /v3/characters/{character_id}/planets/{planet_id}/:
    get:
      description: |-
        Returns full details on the layout of a single planetary colony, including links, pins and routes. Note: Planetary information is only recalculated when the colony is viewed through the client. Information will not update until this criteria is met.

        ---


        SSO Scope: esi-planets.manage_planets.v1
      operationId: get_characters_character_id_planets_planet_id
      security:
      - evesso:
        - esi-planets.manage_planets.v1
      summary: Get colony layout
      tags:
      - Planetary Interaction
      x-alternate-versions:
      - dev
      - v3
      x-accepts:
      - application/json
  /v3/characters/{character_id}/roles/:
    get:
      description: |-
        Returns a character's corporation roles

        ---

        This route is cached for up to 3600 seconds

        SSO Scope: esi-characters.read_corporation_roles.v1
      operationId: get_characters_character_id_roles
      security:
      - evesso:
        - esi-characters.read_corporation_roles.v1
      summary: Get character corporation roles
      tags:
      - Character
      x-alternate-versions:
      - dev
      - v3
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v3/characters/{character_id}/search/:
    get:
      description: |-
        Search for entities that match a given sub-string.

        ---

        This route is cached for up to 3600 seconds

        SSO Scope: esi-search.search_structures.v1
      operationId: get_characters_character_id_search
      security:
      - evesso:
        - esi-search.search_structures.v1
      summary: Search on a string
      tags:
      - Search
      x-alternate-versions:
      - dev
      - legacy
      - v3
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v3/corporations/{corporation_id}/alliancehistory/:
    get:
      description: |-
        Get a list of all the alliances a corporation has been a member of

        ---

        This route is cached for up to 3600 seconds
      operationId: get_corporations_corporation_id_alliancehistory
      summary: Get alliance history
      tags:
      - Corporation
      x-alternate-versions:
      - dev
      - v3
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v3/corporations/{corporation_id}/blueprints/:
    get:
      description: |-
        Returns a list of blueprints the corporation owns

        ---

        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director

        SSO Scope: esi-corporations.read_blueprints.v1
      operationId: get_corporations_corporation_id_blueprints
      security:
      - evesso:
        - esi-corporations.read_blueprints.v1
      summary: Get corporation blueprints
      tags:
      - Corporation
      x-alternate-versions:
      - dev
      - v3
      x-cached-seconds: 3600
      x-required-roles:
      - Director
      x-accepts:
      - application/json
  /v3/corporations/{corporation_id}/containers/logs/:
    get:
      description: |-
        Returns logs recorded in the past seven days from all audit log secure containers (ALSC) owned by a given corporation

        ---

        This route is cached for up to 600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director

        SSO Scope: esi-corporations.read_container_logs.v1
      operationId: get_corporations_corporation_id_containers_logs
      security:
      - evesso:
        - esi-corporations.read_container_logs.v1
      summary: Get all corporation ALSC logs
      tags:
      - Corporation
      x-alternate-versions:
      - dev
      - v3
      x-cached-seconds: 600
      x-required-roles:
      - Director
      x-accepts:
      - application/json
  /v3/corporations/{corporation_id}/wallets/{division}/journal/:
    get:
      description: |-
        Retrieve the given corporation's wallet journal for the given division going 30 days back

        ---

        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Accountant, Junior_Accountant

        SSO Scope: esi-wallet.read_corporation_wallets.v1
      operationId: get_corporations_corporation_id_wallets_division_journal
      security:
      - evesso:
        - esi-wallet.read_corporation_wallets.v1
      summary: Get corporation wallet journal
      tags:
      - Wallet
      x-alternate-versions:
      - dev
      - legacy
      - v3
      - v4
      x-cached-seconds: 3600
      x-required-roles:
      - Accountant
      - Junior_Accountant
      x-accepts:
      - application/json
  /v4/characters/{character_id}/assets/:
    get:
      description: |-
        Return a list of the characters assets

        ---

        This route is cached for up to 3600 seconds

        SSO Scope: esi-assets.read_assets.v1
      operationId: get_characters_character_id_assets
      security:
      - evesso:
        - esi-assets.read_assets.v1
      summary: Get character assets
      tags:
      - Assets
      x-alternate-versions:
      - dev
      - legacy
      - v4
      - v5
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v4/characters/{character_id}/notifications/:
    get:
      description: |-
        Return character notifications

        ---

        This route is cached for up to 600 seconds

        SSO Scope: esi-characters.read_notifications.v1
      operationId: get_characters_character_id_notifications
      security:
      - evesso:
        - esi-characters.read_notifications.v1
      summary: Get character notifications
      tags:
      - Character
      x-alternate-versions:
      - dev
      - legacy
      - v4
      - v5
      - v6
      x-cached-seconds: 600
      x-accepts:
      - application/json
  /v4/characters/{character_id}/skills/:
    get:
      description: |-
        List all trained skills for the given character

        ---

        This route is cached for up to 120 seconds

        SSO Scope: esi-skills.read_skills.v1
      operationId: get_characters_character_id_skills
      security:
      - evesso:
        - esi-skills.read_skills.v1
      summary: Get character skills
      tags:
      - Skills
      x-alternate-versions:
      - dev
      - v4
      x-cached-seconds: 120
      x-accepts:
      - application/json
  /v4/corporations/{corporation_id}/assets/:
    get:
      description: |-
        Return a list of the corporation assets

        ---

        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Director

        SSO Scope: esi-assets.read_corporation_assets.v1
      operationId: get_corporations_corporation_id_assets
      security:
      - evesso:
        - esi-assets.read_corporation_assets.v1
      summary: Get corporation assets
      tags:
      - Assets
      x-alternate-versions:
      - dev
      - legacy
      - v4
      - v5
      x-cached-seconds: 3600
      x-required-roles:
      - Director
      x-accepts:
      - application/json
  /v4/corporations/{corporation_id}/members/:
    get:
      description: |-
        Return the current member list of a corporation, the token's character need to be a member of the corporation.

        ---

        This route is cached for up to 3600 seconds

        SSO Scope: esi-corporations.read_corporation_membership.v1
      operationId: get_corporations_corporation_id_members
      security:
      - evesso:
        - esi-corporations.read_corporation_membership.v1
      summary: Get corporation members
      tags:
      - Corporation
      x-alternate-versions:
      - dev
      - v4
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v4/corporations/{corporation_id}/structures/:
    get:
      description: |-
        Get a list of corporation structures. This route's version includes the changes to structures detailed in this blog: https://www.eveonline.com/article/upwell-2.0-structures-changes-coming-on-february-13th

        ---

        This route is cached for up to 3600 seconds

        ---
        Requires one of the following EVE corporation role(s): Station_Manager

        SSO Scope: esi-corporations.read_structures.v1
      operationId: get_corporations_corporation_id_structures
      security:
      - evesso:
        - esi-corporations.read_structures.v1
      summary: Get corporation structures
      tags:
      - Corporation
      x-alternate-versions:
      - dev
      - v4
      x-cached-seconds: 3600
      x-required-roles:
      - Station_Manager
      x-accepts:
      - application/json
  /v4/universe/systems/{system_id}/:
    get:
      description: |-
        Get information on a solar system.

        ---

        This route expires daily at 11:05
      operationId: get_universe_systems_system_id
      summary: Get solar system information
      tags:
      - Universe
      x-alternate-versions:
      - dev
      - v4
      x-accepts:
      - application/json
  /v5/characters/{character_id}/:
    get:
      description: |-
        Public information about a character

        ---

        This route is cached for up to 604800 seconds
      operationId: get_characters_character_id
      summary: Get character's public information
      tags:
      - Character
      x-alternate-versions:
      - dev
      - legacy
      - v5
      x-cached-seconds: 604800
      x-accepts:
      - application/json
  /v5/characters/{character_id}/cspa/:
    post:
      description: |-
        Takes a source character ID in the url and a set of target character ID's in the body, returns a CSPA charge cost

        ---


        SSO Scope: esi-characters.read_contacts.v1
      operationId: post_characters_character_id_cspa
      security:
      - evesso:
        - esi-characters.read_contacts.v1
      summary: Calculate a CSPA charge cost
      tags:
      - Character
      x-alternate-versions:
      - dev
      - v5
      x-content-type: application/json
      x-accepts:
      - application/json
  /v5/characters/{character_id}/wallet/journal/:
    get:
      description: |-
        Retrieve the given character's wallet journal going 30 days back

        ---

        This route is cached for up to 3600 seconds

        SSO Scope: esi-wallet.read_character_wallet.v1
      operationId: get_characters_character_id_wallet_journal
      security:
      - evesso:
        - esi-wallet.read_character_wallet.v1
      summary: Get character wallet journal
      tags:
      - Wallet
      x-alternate-versions:
      - dev
      - legacy
      - v5
      - v6
      x-cached-seconds: 3600
      x-accepts:
      - application/json
  /v5/corporations/{corporation_id}/:
    get:
      description: |-
        Public information about a corporation

        ---

        This route is cached for up to 3600 seconds
      operationId: get_corporations_corporation_id
      summary: Get corporation information
      tags:
      - Corporation
      x-alternate-versions:
      - dev
      - v5
      x-cached-seconds: 3600
      x-accepts:
      - application/json
components:
  securitySchemes:
    evesso:
      flows:
        implicit:
          authorizationUrl: https://login.eveonline.com/v2/oauth/authorize
          scopes:
            esi-alliances.read_contacts.v1: EVE SSO scope esi-alliances.read_contacts.v1
            esi-assets.read_assets.v1: EVE SSO scope esi-assets.read_assets.v1
            esi-assets.read_corporation_assets.v1: EVE SSO scope esi-assets.read_corporation_assets.v1
            esi-calendar.read_calendar_events.v1: EVE SSO scope esi-calendar.read_calendar_events.v1
            esi-calendar.respond_calendar_events.v1: EVE SSO scope esi-calendar.respond_calendar_events.v1
            esi-characters.read_agents_research.v1: EVE SSO scope esi-characters.read_agents_research.v1
            esi-characters.read_blueprints.v1: EVE SSO scope esi-characters.read_blueprints.v1
            esi-characters.read_contacts.v1: EVE SSO scope esi-characters.read_contacts.v1
            esi-characters.read_corporation_roles.v1: EVE SSO scope esi-characters.read_corporation_roles.v1
            esi-characters.read_fatigue.v1: EVE SSO scope esi-characters.read_fatigue.v1
            esi-characters.read_fw_stats.v1: EVE SSO scope esi-characters.read_fw_stats.v1
            esi-characters.read_loyalty.v1: EVE SSO scope esi-characters.read_loyalty.v1
            esi-characters.read_medals.v1: EVE SSO scope esi-characters.read_medals.v1
            esi-characters.read_notifications.v1: EVE SSO scope esi-characters.read_notifications.v1
            esi-characters.read_standings.v1: EVE SSO scope esi-characters.read_standings.v1
            esi-characters.read_titles.v1: EVE SSO scope esi-characters.read_titles.v1
            esi-characters.write_contacts.v1: EVE SSO scope esi-characters.write_contacts.v1
            esi-clones.read_clones.v1: EVE SSO scope esi-clones.read_clones.v1
            esi-clones.read_implants.v1: EVE SSO scope esi-clones.read_implants.v1
            esi-contracts.read_character_contracts.v1: EVE SSO scope esi-contracts.read_character_contracts.v1
            esi-contracts.read_corporation_contracts.v1: EVE SSO scope esi-contracts.read_corporation_contracts.v1
            esi-corporations.read_blueprints.v1: EVE SSO scope esi-corporations.read_blueprints.v1
            esi-corporations.read_contacts.v1: EVE SSO scope esi-corporations.read_contacts.v1
            esi-corporations.read_container_logs.v1: EVE SSO scope esi-corporations.read_container_logs.v1
            esi-corporations.read_corporation_membership.v1: EVE SSO scope esi-corporations.read_corporation_membership.v1
            esi-corporations.read_divisions.v1: EVE SSO scope esi-corporations.read_divisions.v1
            esi-corporations.read_facilities.v1: EVE SSO scope esi-corporations.read_facilities.v1
            esi-corporations.read_fw_stats.v1: EVE SSO scope esi-corporations.read_fw_stats.v1
            esi-corporations.read_medals.v1: EVE SSO scope esi-corporations.read_medals.v1
            esi-corporations.read_standings.v1: EVE SSO scope esi-corporations.read_standings.v1
            esi-corporations.read_starbases.v1: EVE SSO scope esi-corporations.read_starbases.v1
            esi-corporations.read_structures.v1: EVE SSO scope esi-corporations.read_structures.v1
            esi-corporations.read_titles.v1: EVE SSO scope esi-corporations.read_titles.v1
            esi-corporations.track_members.v1: EVE SSO scope esi-corporations.track_members.v1
            esi-fittings.read_fittings.v1: EVE SSO scope esi-fittings.read_fittings.v1
            esi-fittings.write_fittings.v1: EVE SSO scope esi-fittings.write_fittings.v1
            esi-fleets.read_fleet.v1: EVE SSO scope esi-fleets.read_fleet.v1
            esi-fleets.write_fleet.v1: EVE SSO scope esi-fleets.write_fleet.v1
            esi-industry.read_character_jobs.v1: EVE SSO scope esi-industry.read_character_jobs.v1
            esi-industry.read_character_mining.v1: EVE SSO scope esi-industry.read_character_mining.v1
            esi-industry.read_corporation_jobs.v1: EVE SSO scope esi-industry.read_corporation_jobs.v1
            esi-industry.read_corporation_mining.v1: EVE SSO scope esi-industry.read_corporation_mining.v1
            esi-killmails.read_corporation_killmails.v1: EVE SSO scope esi-killmails.read_corporation_killmails.v1
            esi-killmails.read_killmails.v1: EVE SSO scope esi-killmails.read_killmails.v1
            esi-location.read_location.v1: EVE SSO scope esi-location.read_location.v1
            esi-location.read_online.v1: EVE SSO scope esi-location.read_online.v1
            esi-location.read_ship_type.v1: EVE SSO scope esi-location.read_ship_type.v1
            esi-mail.organize_mail.v1: EVE SSO scope esi-mail.organize_mail.v1
            esi-mail.read_mail.v1: EVE SSO scope esi-mail.read_mail.v1
            esi-mail.send_mail.v1: EVE SSO scope esi-mail.send_mail.v1
            esi-markets.read_character_orders.v1: EVE SSO scope esi-markets.read_character_orders.v1
            esi-markets.read_corporation_orders.v1: EVE SSO scope esi-markets.read_corporation_orders.v1
            esi-markets.structure_markets.v1: EVE SSO scope esi-markets.structure_markets.v1
            esi-planets.manage_planets.v1: EVE SSO scope esi-planets.manage_planets.v1
            esi-planets.read_customs_offices.v1: EVE SSO scope esi-planets.read_customs_offices.v1
            esi-search.search_structures.v1: EVE SSO scope esi-search.search_structures.v1
            esi-skills.read_skillqueue.v1: EVE SSO scope esi-skills.read_skillqueue.v1
            esi-skills.read_skills.v1: EVE SSO scope esi-skills.read_skills.v1
            esi-ui.open_window.v1: EVE SSO scope esi-ui.open_window.v1
            esi-ui.write_waypoint.v1: EVE SSO scope esi-ui.write_waypoint.v1
            esi-universe.read_structures.v1: EVE SSO scope esi-universe.read_structures.v1
            esi-wallet.read_character_wallet.v1: EVE SSO scope esi-wallet.read_character_wallet.v1
            esi-wallet.read_corporation_wallets.v1: EVE SSO scope esi-wallet.read_corporation_wallets.v1
      type: oauth2
x-original-swagger-version: "2.0"

